### ISSUE TITLE
[BUG] ImportError: cannot import name 'is_functional' from 'tensordict.nn'

### ISSUE THREAD

**Issue by likunshu** [pytorch/rl#1050]
## Describe the bug

When running `import torchrl`, the error occurs.

## To Reproduce

```bash
conda create -n rl python=3.9
conda activate rl
conda install pytorch torchvision torchaudio -c pytorch
conda install -c conda-forge tensordict
git clone https://github.com/pytorch/rl
cd /somewhere/rl
pip install -e .
python -c "import torchrl"

```

```bash
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/Kunshu/opt/anaconda3/pkgs/rl-main/torchrl/__init__.py", line 36, in <module>
    import torchrl.objectives
  File "/Users/Kunshu/opt/anaconda3/pkgs/rl-main/torchrl/objectives/__init__.py", line 6, in <module>
    from .a2c import A2CLoss
  File "/Users/Kunshu/opt/anaconda3/pkgs/rl-main/torchrl/objectives/a2c.py", line 13, in <module>
    from torchrl.objectives.common import LossModule
  File "/Users/Kunshu/opt/anaconda3/pkgs/rl-main/torchrl/objectives/common.py", line 22, in <module>
    from torchrl.objectives.value import ValueEstimatorBase
  File "/Users/Kunshu/opt/anaconda3/pkgs/rl-main/torchrl/objectives/value/__init__.py", line 6, in <module>
    from .advantages import (
  File "/Users/Kunshu/opt/anaconda3/pkgs/rl-main/torchrl/objectives/value/advantages.py", line 11, in <module>
    from tensordict.nn import dispatch, is_functional, TensorDictModule
ImportError: cannot import name 'is_functional' from 'tensordict.nn' (/Users/kunshu/opt/anaconda3/envs/rl/lib/python3.9/site-packages/tensordict/nn/__init__.py)
```

## System info

macOS Ventura 13.3.1
python==3.9.16
torch==2.0.0
tensordict==0.1.0+77f76ad

## Checklist

- I have checked that there is no similar issue in the repo (**required**)
- I have read the [documentation](https://github.com/pytorch/rl/tree/main/docs/) (**required**)
- I have provided a minimal working example to reproduce the bug (**required**)

**Comment by likunshu** [comment]
It seems resulted from the fact that `is_functional` is moved to a sub module called `tensordict.nn.functional_modules`.

The issue resolves after modify following line in `advantages.py` from :

```pytthon
from tensordict.nn import dispatch, is_functional, TensorDictModule
```

to


```pytthon
from tensordict.nn import dispatch,TensorDictModule
from tensordict.nn.functional_modules import is_functional
```

**Comment by vmoens** [comment]
Currently, torchrl and tensordict are being developped in parallel. If you're installing torchrl from the git repo, you should do the same with tensordict (either via a clone or via `pip install git+https://github.com/pytorch-labs/tensordict`).
This should solve your issue

**Comment by likunshu** [comment]
I see where the problem lies, thank you for the kindness support!
