### ISSUE TITLE
[BUG] _reset tensor unexpectedly modified, causing crashes

### ISSUE THREAD

**Issue by SiliconSloth** [pytorch/rl#1167]
## Describe the bug

When running `examples/ppo/ppo.py` the program randomly crashes after a few thousand iterations with one of various errors such as:
```
Traceback (most recent call last):
  File "examples\ppo\ppo.py", line 78, in main
    for data in collector:
  File "torchrl\collectors\collectors.py", line 731, in iterator
    tensordict_out = self.rollout()
  File "torchrl\_utils.py", line 361, in unpack_rref_and_invoke_function
    return func(self, *args, **kwargs)
  File "torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "torchrl\collectors\collectors.py", line 826, in rollout
    self.env.step(self._tensordict)
  File "torchrl\envs\common.py", line 378, in step
    tensordict_out = self._step(tensordict)
  File "torchrl\envs\transforms\transforms.py", line 583, in _step
    tensordict_out = self.base_env._step(tensordict_in)
  File "torchrl\envs\vec_env.py", line 49, in decorated_fun
    return fun(self, *args, **kwargs)
  File "torchrl\envs\vec_env.py", line 736, in _step
    raise RuntimeError(
RuntimeError: Expected 'step_result' but received reset_obs from worker 6
```

```
  File "examples\ppo\ppo.py", line 78, in main
    for data in collector:
  File "torchrl\collectors\collectors.py", line 731, in iterator
    tensordict_out = self.rollout()
  File "torchrl\_utils.py", line 361, in unpack_rref_and_invoke_function
    return func(self, *args, **kwargs)
  File "venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "torchrl\collectors\collectors.py", line 842, in rollout
    self._step_and_maybe_reset()
  File "torchrl\collectors\collectors.py", line 796, in _step_and_maybe_reset
    raise RuntimeError(
RuntimeError: Env TransformedEnv(
    env=ParallelEnv(
        env=GymEnv(env=PongNoFrameskip-v4, batch_size=torch.Size([]), device=cpu),
        batch_size=torch.Size([8])),
    transform=Compose(
            RewardScaling(loc=0.0000, scale=0.0000, keys=['reward']),
            ToTensorImage(keys=['pixels']),
            GrayScale(keys=['pixels']),
            Resize(w=84, h=84, interpolation=InterpolationMode.BILINEAR, keys=['pixels']),
            CatFrames(N=4, dim=-3, keys=['pixels']),
            RewardSum(keys=['reward']),
            StepCounter(keys=[]),
            DoubleToFloat(in_keys=[], out_keys=[], in_keys_inv=[], out_keys_inv=[]))) was done after reset on specified '_reset' dimensions. This is (currently) not allowed.
```

After some digging I found that these errors seem to have one root cause, which is that the `_reset` tensor in `torchrl\envs\vec_env.py : ParallelEnv : _reset()` is modified between the calls to `channel.send()` and `channel.recv()`.  This means some channels have `send()` called but not `recv()`, causing messages to become out of sync between different functions.  This unexpected modification of `_reset` also causes other errors such as the one above in functions that reference this tensor.

The modification to `_reset` can be detected by replacing the code of the `ParallelEnv : reset()` function with the following:

```python
    @_check_start
    def _reset(self, tensordict: TensorDictBase, **kwargs) -> TensorDictBase:
        cmd_out = "reset"
        if tensordict is not None and "_reset" in tensordict.keys():
            self._assert_tensordict_shape(tensordict)
            _reset = tensordict.get("_reset")
            if _reset.shape[-len(self.done_spec.shape) :] != self.done_spec.shape:
                raise RuntimeError(
                    "_reset flag in tensordict should follow env.done_spec"
                )
        else:
            _reset = torch.ones(
                self.done_spec.shape, dtype=torch.bool, device=self.device
            )
        # Original values
        reset_copy = _reset.cpu().numpy()

        for i, channel in enumerate(self.parent_channels):
            if tensordict is not None:
                tensordict_ = tensordict[i]
                if tensordict_.is_empty():
                    tensordict_ = None
            else:
                tensordict_ = None
            kwargs["tensordict"] = tensordict_
            if not _reset[i].any():
                self.shared_tensordicts[i].update_(
                    self.shared_tensordicts[i]["next"].select(
                        *self._selected_reset_keys, strict=False
                    )
                )
                if kwargs["tensordict"] is not None:
                    self.shared_tensordicts[i].update_(
                        kwargs["tensordict"].select(
                            *self._selected_reset_keys, strict=False
                        )
                    )
                # we must update the
                continue
            # Always seems to be fine here
            reset_copy2 = _reset.cpu().numpy()
            assert (reset_copy == reset_copy2).all()
            channel.send((cmd_out, kwargs))
            # Eventually changes here
            reset_copy2 = _reset.cpu().numpy()
            assert (reset_copy == reset_copy2).all()

        for i, channel in enumerate(self.parent_channels):
            if not _reset[i].any():
                continue
            cmd_in, data = channel.recv()
            if cmd_in != "reset_obs":
                raise RuntimeError(f"received cmd {cmd_in} instead of reset_obs")
            if data is not None:
                self.shared_tensordicts[i].update_(data)

        return self.shared_tensordict_parent.select(*self._selected_reset_keys).clone()
```

I've also sometimes had a few other unexpected tensor changes, such as the GAE gamma and lambda parameter tensors suddenly being set to zero many iterations into execution.

## System info

TorchRL library cloned from GitHub, main branch.
Python version 3.9.1 (tags/v3.9.1:1e5d33e, Dec  7 2020, 17:08:21) [MSC v.1927 64 bit (AMD64)] win32
Windows 10, CUDA 11.8

Pip packages:
```
ale-py                 0.8.1
antlr4-python3-runtime 4.9.3
appdirs                1.4.4
certifi                2022.12.7
charset-normalizer     2.1.1
click                  8.1.3
cloudpickle            2.2.1
colorama               0.4.6
docker-pycreds         0.4.0
filelock               3.9.0
gitdb                  4.0.10
GitPython              3.1.31
gym                    0.26.2
gym-notices            0.0.8
hydra-core             1.3.2
idna                   3.4
importlib-metadata     6.6.0
importlib-resources    5.12.0
Jinja2                 3.1.2
MarkupSafe             2.1.2
mpmath                 1.2.1
networkx               3.0
numpy                  1.24.1
omegaconf              2.3.0
packaging              23.1
pathtools              0.1.2
Pillow                 9.3.0
pip                    23.1.2
protobuf               4.23.1
psutil                 5.9.5
PyYAML                 6.0
requests               2.28.1
sentry-sdk             1.23.1
setproctitle           1.3.2
setuptools             49.2.1
six                    1.16.0
smmap                  5.0.0
sympy                  1.11.1
tensordict             0.1.2
tensordict-nightly     2023.5.15
torch                  2.0.1+cu118
torchaudio             2.0.2+cu118
torchrl                0.1.1+3fb2d0d
torchvision            0.15.2
tqdm                   4.65.0
typing_extensions      4.4.0
urllib3                1.26.13
viskit                 0.1
wandb                  0.15.3
zipp                   3.15.0
```

## Checklist

- [x] I have checked that there is no similar issue in the repo (**required**)
- [x] I have read the [documentation](https://github.com/pytorch/rl/tree/main/docs/) (**required**)
- [x] I have provided a minimal working example to reproduce the bug (**required**)

**Comment by vmoens** [comment]
Thanks for reporting this and for investigating it thoroughly @SiliconSloth 
We're in the process of refactoring the parallel env communication using queues (https://github.com/pytorch/rl/pull/1166)
We defo need to avoid race conditions at all cost. 
I'm a bit puzzled by what the underlying cause of this might be though. 
With queues I found that cloning and putting the _reset in shared memory before sending the tensor to the remote process helped solving these kinds of bugs.
I'll keep you posted on the progress and make sure that we test the feature thoroughly before landing!

**Comment by vmoens** [comment]
CLosing as I think this is solved now, feel free to reopen if not
