### ISSUE TITLE
[BUG] TD3 loss mixes actor and critic grads

### ISSUE THREAD

**Issue by smorad** [pytorch/rl#1187]
## Describe the bug
Sorry for the wave of issues, I am just trying to implement various baselines.

I believe that the TD3 loss might accidentally leak critic gradients into the actor.

## To Reproduce
If we take a working DDPG script with separate actor/critic optimizers and repurpose it for TD3, we get 
```bash
Traceback (most recent call last):
  File "/Users/smorad/code/pql/td3_torchrl.py", line 109, in <module>
    loss["loss_qvalue"].backward()
  File "/Users/smorad/miniforge3/envs/torch_rl/lib/python3.9/site-packages/torch/_tensor.py", line 487, in backward
    torch.autograd.backward(
  File "/Users/smorad/miniforge3/envs/torch_rl/lib/python3.9/site-packages/torch/autograd/__init__.py", line 200, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: Trying to backward through the graph a second time (or directly access saved tensors after they have already been freed). Saved intermediate values of the graph are freed when you call .backward() or autograd.grad(). Specify retain_graph=True if you need to backward through the graph a second time or if you need to access saved tensors after calling backward.
```

```python
import tqdm
from torchrl.data.replay_buffers.samplers import SamplerWithoutReplacement
from torchrl.data.replay_buffers.storages import LazyTensorStorage
from torchrl.envs.libs.dm_control import DMControlEnv
from torchrl.envs.libs.gym import GymEnv
import torchrl
from torchrl.envs.transforms.transforms import Compose, RewardSum, RewardScaling
from torchrl.objectives import DDPGLoss
from torchrl.data import ReplayBuffer, ListStorage, TensorDictReplayBuffer
from torchrl.modules import (
    ConvNet,
    EGreedyWrapper,
    LSTMModule,
    MLP,
    QValueModule,
    TanhDelta,
)
from tensordict.nn import TensorDictModule as Mod, TensorDictSequential as Seq
from torch import nn
import torch
from torchrl.envs.transforms import DoubleToFloat, TransformedEnv
from torchrl.modules.tensordict_module.actors import ProbabilisticActor, ValueOperator
from torchrl.modules.tensordict_module.exploration import AdditiveGaussianWrapper
from torchrl.objectives.td3 import TD3Loss
from torchrl.objectives.utils import SoftUpdate, ValueEstimators
from torchrl.data.replay_buffers.samplers import PrioritizedSampler

class CriticNet(nn.Module):
    def __init__(self, obs_size, act_size):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(obs_size + act_size, 400),
            nn.ReLU(),
            nn.Linear(400, 300),
            nn.ReLU(),
            nn.Linear(300, 1),
        )
        nn.init.normal_(self.net[-1].weight, 0, 0.001)
        self.net[-1].bias.data.zero_()

    def forward(self, observation, action):
        return self.net(torch.cat([observation, action], dim=-1))


class ActorNet(nn.Module):
    def __init__(self, obs_size):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(obs_size, 400),
            nn.ReLU(),
            nn.Linear(400, 300),
            nn.ReLU(),
            nn.Linear(300, 1),
        )
        nn.init.normal_(self.net[-1].weight, 0, 0.001)
        self.net[-1].bias.data.zero_()

    def forward(self, observation):
        return self.net(observation)

# Config
seed = 0
gamma = 0.99
tau = 0.005
frames_per_batch = 200  # Frames sampled each sampling iteration
batch_size = 200  # in terms of rollout size
utd = 64 # update to data ratio
n_iters = 500  # Number of sampling/training iterations
warmup_frames = 100  # To prefill replay buffer
total_frames = frames_per_batch * n_iters
memory_size = frames_per_batch * 100
lr = 0.001

torch.manual_seed(0)


def env():
    env = GymEnv("Pendulum-v1", from_pixels=False)
    env = TransformedEnv(
        env, Compose(DoubleToFloat(in_keys=["observation"]), RewardSum(), RewardScaling(loc=0.0, scale=0.1))
    )
    return env


proof_env = env()
obs_size = proof_env.observation_spec["observation"].shape[0]
act_size = proof_env.action_spec.shape[0]

actor_mod = Mod(ActorNet(obs_size), in_keys=["observation"], out_keys=["param"])
actor = ProbabilisticActor(
    module=actor_mod,
    spec=proof_env.action_spec,
    in_keys=["param"],
    distribution_class=TanhDelta,
    distribution_kwargs={
        "min": proof_env.action_spec.space.minimum,
        "max": proof_env.action_spec.space.maximum,
    },
    return_log_prob=False,
)
policy = AdditiveGaussianWrapper(
    actor, annealing_num_steps=int(total_frames), sigma_end=0.1, spec=proof_env.action_spec,
)

critic = ValueOperator(CriticNet(obs_size, act_size), in_keys=["observation", "action"])

collector = torchrl.collectors.SyncDataCollector(
    env,
    policy,
    frames_per_batch=frames_per_batch,
    total_frames=total_frames,
)
buffer = TensorDictReplayBuffer(storage=LazyTensorStorage(memory_size), batch_size=batch_size)

loss_module = TD3Loss(
    actor_network=actor,
    qvalue_network=critic,
    delay_qvalue=True,
    num_qvalue_nets=2,
    loss_function="l2",
    policy_noise=0.2,
    noise_clip=0.5,
)
loss_module.make_value_estimator(gamma=gamma)
target_net_updater = SoftUpdate(loss_module, eps=1 - tau)

actor_opt = torch.optim.Adam(actor.parameters(), lr)
critic_opt = torch.optim.Adam(critic.parameters(), lr)

pbar = tqdm.tqdm(total=total_frames)
for i, tensordict in enumerate(collector):
    pbar.update(tensordict.numel())
    buffer.extend(tensordict)
    for j in range(utd):
        data = buffer.sample()
        loss = loss_module(data)
        critic_opt.zero_grad()
        actor_opt.zero_grad()
        loss["loss_actor"].backward()
        loss["loss_qvalue"].backward()
        critic_opt.step()
        actor_opt.step()
        pbar.set_description(
            "Epoch {}: episode reward {:.2f} actor loss {:.2f}, critic loss {:.2f}".format(
                i,
                tensordict['next']["episode_reward"][tensordict['next']['done']].mean(),
                loss["loss_actor"].item(),
                loss["loss_qvalue"].item(),
            )
        )
        target_net_updater.step()
    policy.step(tensordict.numel())
    collector.update_policy_weights_()
```

## Expected behavior

Separate optimizer calls for actor/critic should not crash.

## System info
master

## Reason and Possible fixes

I _think_ the issue might be here but I could be wrong:

https://github.com/pytorch/rl/blob/1e17304cb0732d2f30bef2c15e0e6a0172d9feb8/torchrl/objectives/td3.py#L181-L196

I checked and `tensordict_qval.requires_grad=True`, where the grad corresponds to the weights of the learned (not target) Q function. So when you split it into `state_action_value_vector`, you have some dangling Q grads going into the `loss_actor`.
## Checklist

- [x] I have checked that there is no similar issue in the repo (**required**)
- [x] I have read the [documentation](https://github.com/pytorch/rl/tree/main/docs/) (**required**)
- [x] I have provided a minimal working example to reproduce the bug (**required**)

**Comment by vmoens** [comment]
Thanks for spotting this
cc @BY571 who had a similar question just 10 mins ago
I don't think we mix gradients but it appears it is.
I will fix this, but here's the context

To minimize calls to some modules, we functionalize everything and try to group the computation using vmap.
What happens is that if you do
```
_tensordict = torch.stack([tensordict, tensordict.get("next")])
_params = torch.stack([params, target_params])
vmap(net)(_tensordict, _params)
```
then the results of the call to target and non target will be part of the same graph even though the second half (the target) will carry 0 gradient effectively.
Once you free the graph of the actor, you also free the one of the critic. It's suboptimal and we should keep them separated. 
We actually test that the gradients are 0 for the critic when you backprop the actor and vice versa.
Again, suboptimal but not a real "bug".
While you're waiting for me to land a fix, feel free to patch your backward with a `retain_graph=True`.

Hope that helps!

**Comment by vmoens** [comment]
@BY571 we should create isolated method to compute the loss of the actor and critic to avoid this.
This is not urgent :)

**Comment by BY571** [comment]
In the updated example I will split the actor/critic loss computations then.

**Comment by vmoens** [comment]
Thanks
Can I ask you to check if any gradient of the critic has a norm > 0 after calling `loss["loss_actor"].backward(retain_graph=True)`? That shouldn't be the case

**Comment by smorad** [comment]
Yes, my mistake.

```python
        data = buffer.sample()
        loss = loss_module(data)
        critic_opt.zero_grad()
        actor_opt.zero_grad()
        loss["loss_actor"].backward(retain_graph=True)
        grads = [p.grad for p in critic.parameters() if p.grad]
        breakpoint()
```
```
(Pdb) grads
[]
```
Okay this seems fine. I'll keep looking.

**Comment by vmoens** [comment]
This is fixed I believe but happy to reopen if needed!
