### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by hchaozhe** [pytorch/rl#1394]
I was trying to use torchrl 0.1.1 in a docker with python 3.8.
I installed torchrl using
```
RUN pip3 install torchrl==0.1.1
```
When I try to run the [coding.dqn](tutorials/sphinx-tutorials/coding_dqn.py) example I encountered the following error
```shell
Traceback (most recent call last):
  File "coding_dqn.py", line 562, in <module>
    stats = get_norm_stats()
  File "coding_dqn.py", line 253, in get_norm_stats
    test_env = make_env()
  File "coding_dqn.py", line 216, in make_env
    base_env = GymEnv(
  File "/usr/local/lib/python3.8/dist-packages/torchrl/envs/libs/gym.py", line 588, in __init__
    self._set_gym_args(kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torchrl/_utils.py", line 300, in unsupported
    raise ModuleNotFoundError(
ModuleNotFoundError: Supported version of '_set_gym_args' has not been found.
```
Is this because some dependents need to be installed?
Thank you

**Comment by vmoens** [comment]
Have installed gym or gymnasium too?

**Comment by hchaozhe** [comment]
Thanks! @vmoens I also tried myself. Indeed I resolved by add the following command 
```
pip3 install "gym[atari]" "gym[accept-rom-license]" pygame
```
