### ISSUE TITLE
[Feature Request] Readable error messages

### ISSUE THREAD

**Issue by smorad** [pytorch/rl#1415]
## Motivation

Many stack traces output by torchrl are long and confusing. It would improve user experience if these were more readable. Here's one example, where I have an error in my `TensorDictModule` which is wrapped in an `EGreedyWrapper` (a relatively common mistake):

```python
Traceback (most recent call last):
  File "/Users/smorad/code/from_src/tensordict/tensordict/nn/common.py", line 1178, in forward
    raise err
  File "/Users/smorad/code/from_src/tensordict/tensordict/nn/common.py", line 1164, in forward
    tensors = self._call_module(tensors, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/smorad/code/from_src/tensordict/tensordict/nn/common.py", line 1121, in _call_module
    out = self.module(*tensors, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/smorad/miniforge3/envs/rdqn/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/smorad/code/from_src/tensordict/tensordict/nn/functional_modules.py", line 555, in new_fun
    out = getattr(type(self), fun_name)(self, *args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Sequential.forward() missing 1 required positional argument: 'input'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/smorad/code/rqdn/dqn.py", line 99, in <module>
    policy(env.reset())
  File "/Users/smorad/miniforge3/envs/rdqn/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/smorad/code/from_src/torchrl/torchrl/modules/tensordict_module/exploration.py", line 132, in forward
    tensordict = self.td_module.forward(tensordict)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/smorad/code/from_src/tensordict/tensordict/nn/functional_modules.py", line 555, in new_fun
    out = getattr(type(self), fun_name)(self, *args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/smorad/code/from_src/tensordict/tensordict/nn/common.py", line 279, in wrapper
    out = func(_self, tensordict, *args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/smorad/code/from_src/tensordict/tensordict/_contextlib.py", line 126, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/smorad/code/from_src/tensordict/tensordict/nn/utils.py", line 253, in wrapper
    return func(_self, tensordict, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/smorad/code/from_src/tensordict/tensordict/nn/sequence.py", line 426, in forward
    tensordict = self._run_module(module, tensordict, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/smorad/code/from_src/tensordict/tensordict/nn/sequence.py", line 407, in _run_module
    tensordict = module(tensordict, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/smorad/miniforge3/envs/rdqn/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/smorad/code/from_src/tensordict/tensordict/nn/functional_modules.py", line 555, in new_fun
    out = getattr(type(self), fun_name)(self, *args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/smorad/code/from_src/tensordict/tensordict/nn/common.py", line 279, in wrapper
    out = func(_self, tensordict, *args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/smorad/code/from_src/tensordict/tensordict/_contextlib.py", line 126, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/smorad/code/from_src/tensordict/tensordict/nn/utils.py", line 253, in wrapper
    return func(_self, tensordict, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/smorad/code/from_src/tensordict/tensordict/nn/common.py", line 1204, in forward
    raise RuntimeError(
RuntimeError: TensorDictModule failed with operation
    Sequential(
      (0): Linear(in_features=128, out_features=64, bias=False)
      (1): Mish()
      (2): Linear(in_features=64, out_features=64, bias=False)
      (3): Mish()
      (4): Linear(in_features=64, out_features=2, bias=False)
    )
    in_keys=['markov_state']
    out_keys=['action_value'].
```

First off, it's not entirely clear __where__ the error in my code is even occurring. I need to scroll to the second traceback to see `File "/Users/smorad/code/rqdn/dqn.py", line 99, in <module>`. Then, there is a mess of functional calls like `getattr(type(self), fun_name)(self, *args, **kwargs)` or `return func(*args, **kwargs)` which are arguably useless to end users. Finally, we reach the bottom and see `RuntimeError: TensorDictModule failed with operation`, which gives us a hint at which module is failing. Then, we need to scroll back up to find the error this module raised, which is `TypeError: Sequential.forward() missing 1 required positional argument: 'input`.

## Solution

When an exception is raised in a `TensorDictModule`, it could be much shorter, and the 
1. Line in user code where the error occurred
2. Exception raised in the `TensorDictModule`
3. Description of the `TensorDictModule`

could all occur in the same block of text. The long stack trace could still be accessible by setting a flag like `torchrl.verbose_stacktrace(True)`.

## Checklist

- [x] I have checked that there is no similar issue in the repo (**required**)

**Comment by vmoens** [comment]
This has been solved in tensordict so closing it
