### ISSUE TITLE
[BUG] DoubleToFloat transform deletes keys

### ISSUE THREAD

**Issue by smorad** [pytorch/rl#1437]
## Describe the bug

The `DoubleToFloat` transform appears to delete all input keys, and will break any environment it is attached to.

## To Reproduce

Steps to reproduce the behavior.

```python
from torchrl.envs import DoubleToFloat, TransformedEnv, Compose
from torchrl.envs.libs.gym import GymEnv
GymEnv("CartPole-v0").reset()
```
```python
TensorDict(
    fields={
        done: Tensor(shape=torch.Size([1]), device=cpu, dtype=torch.bool, is_shared=False),
        observation: Tensor(shape=torch.Size([4]), device=cpu, dtype=torch.float32, is_shared=False)},
    batch_size=torch.Size([]),
    device=cpu,
    is_shared=False)
```
```python
TransformedEnv(GymEnv("CartPole-v0"), Compose(DoubleToFloat())).reset()
```
```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/smorad/code/from_src/torchrl/torchrl/envs/common.py", line 944, in reset
    tensordict_reset = self._reset(tensordict, **kwargs)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/smorad/code/from_src/torchrl/torchrl/envs/transforms/transforms.py", line 655, in _reset
    out_tensordict = self.transform._call(out_tensordict)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/smorad/code/from_src/torchrl/torchrl/envs/transforms/transforms.py", line 836, in _call
    tensordict = t._call(tensordict)
                 ^^^^^^^^^^^^^^^^^^^
  File "/Users/smorad/code/from_src/torchrl/torchrl/envs/transforms/transforms.py", line 201, in _call
    for in_key, out_key in zip(self.in_keys, self.out_keys):
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not iterable
```

## Expected behavior

Not crash

## System info

master, commit d500488f4e75d482792251725125568751360ccd

## Reason and Possible fixes

If you know or suspect the reason for this bug, paste the code lines and suggest modifications.

## Checklist

- [x] I have checked that there is no similar issue in the repo (**required**)
- [x] I have read the [documentation](https://github.com/pytorch/rl/tree/main/docs/) (**required**)
- [x] I have provided a minimal working example to reproduce the bug (**required**)

**Comment by smorad** [comment]
Yeah I did figure it out afterwards. But this crash made me dig through the torchrl source code to understand what was going on. Ideally this wouldn't happen to other users. Maybe I should make `in_keys` not optional, so the constructor errors out if you don't pass `in_keys`, rather than crashing when the collector runs.
