### ISSUE TITLE
Error message when importing torchrl

### ISSUE THREAD

**Issue by gy2256** [pytorch/rl#1447]
## Describe the bug

Unable to import torchrl

## To Reproduce

`import torchrl`

```Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mac/research_code/others_code/rl/torchrl/__init__.py", line 32, in <module>
    import torchrl.collectors
  File "/Users/mac/research_code/others_code/rl/torchrl/collectors/__init__.py", line 6, in <module>
    from .collectors import (
  File "/Users/mac/research_code/others_code/rl/torchrl/collectors/collectors.py", line 39, in <module>
    from torchrl.data.tensor_specs import TensorSpec
  File "/Users/mac/research_code/others_code/rl/torchrl/data/__init__.py", line 6, in <module>
    from . import datasets
  File "/Users/mac/research_code/others_code/rl/torchrl/data/datasets/__init__.py", line 1, in <module>
    from .d4rl import D4RLExperienceReplay
  File "/Users/mac/research_code/others_code/rl/torchrl/data/datasets/d4rl.py", line 14, in <module>
    from torchrl.data.replay_buffers import TensorDictReplayBuffer
  File "/Users/mac/research_code/others_code/rl/torchrl/data/replay_buffers/__init__.py", line 6, in <module>
    from .replay_buffers import (
  File "/Users/mac/research_code/others_code/rl/torchrl/data/replay_buffers/replay_buffers.py", line 47, in <module>
    from torchrl.data.utils import DEVICE_TYPING
  File "/Users/mac/research_code/others_code/rl/torchrl/data/utils.py", line 14, in <module>
    from torchrl.data.tensor_specs import (
  File "/Users/mac/research_code/others_code/rl/torchrl/data/tensor_specs.py", line 34, in <module>
    from tensordict import unravel_key
ImportError: cannot import name 'unravel_key' from 'tensordict' (/opt/anaconda3/envs/rl-mpc/lib/python3.10/site-packages/tensordict/__init__.py)
```

Please use the markdown code blocks for both code and stack traces.

## Expected behavior

The torchrl library should be loaded without error message. 

## System info
Mac OS Ventura 13.5 (with M1 Pro)
Python 3.10.12
torchrl

```python

print(tensordict.__version__, numpy.__version__, sys.version, sys.platform, torch.__version__)

2023.06.08 1.24.3 3.10.12 (main, Jul  5 2023, 15:02:25) [Clang 14.0.6 ] darwin 2.0.1
```

**Comment by vmoens** [comment]
You're most likely using the nighties from torchrl but not tensordict. Install the main branch of tensordict (or nightly built) and you should be fine

**Comment by gy2256** [comment]
Thanks! I think that was the issue. It worked after I reinstalled both torchrl and tensordict using their latest official releases.
