### ISSUE TITLE
[BUG] Ensembles do not work with losses that use convert_to_functional

### ISSUE THREAD

**Issue by smorad** [pytorch/rl#1452]
## Describe the bug

The tensordict `EnsembleModule` does not work with `DQNLoss` (and possibly other losses) due to the use of `convert_to_functional`. The combination of the ensemble at the module-level and target network at the loss level seems less than ideal, and is something I didn't think enough about while implementing the `EnsembleModule`. Both the `EnsembleModule` and the `DQNLoss` want to "own" the network parameters. Would it make sense to pull the target networks out of the losses e.g., with a `WithTargetNetworkModule` that we can call `step()` on? Or explicitly pass separate q/target nets to the `DQNLoss` constructor?

## To Reproduce

```python
import gymnasium as gym
from torchrl.envs.libs.gym import GymWrapper
from tensordict.nn import TensorDictModule as Mod, TensorDictSequential as Seq, EnsembleModule, TensorDictModuleBase
from torch import nn
import tensordict
from torchrl.modules import QValueModule
from torchrl.objectives import DQNLoss
from torchrl.envs.libs.gym import GymWrapper
from typing import Union, List


env = GymWrapper(gym.make("CartPole-v0"))
class MinReduce(TensorDictModuleBase):
    def __init__(self, reduce_key: Union[List[str], str]):
        super().__init__()
        self.reduce_key = reduce_key
        self.in_keys = [reduce_key]
        self.out_keys = []

    def forward(self, td):
        min_idx = td.get(self.reduce_key).argmin(0)
        return td[min_idx]


ensemble = Seq(
    EnsembleModule(
        Mod(nn.Linear(2, 3), in_keys=["observation"], out_keys=["action_value"]),
        num_copies=2
    ),
    MinReduce("action_value"),
    QValueModule(action_space=env.action_spec),
)
loss_fn = DQNLoss(
    ensemble,
    delay_value=True,
    action_space=env.action_spec,
)
```

```python
Traceback (most recent call last):
  File "/Users/smorad/code/rqdn/test.py", line 34, in <module>
    loss_fn = DQNLoss(
              ^^^^^^^^
  File "/Users/smorad/code/from_src/torchrl/torchrl/objectives/dqn.py", line 175, in __init__
    self.convert_to_functional(
  File "/Users/smorad/code/from_src/torchrl/torchrl/objectives/common.py", line 248, in convert_to_functional
    functional_module = deepcopy(module)
                        ^^^^^^^^^^^^^^^^
  File "/Users/smorad/miniforge3/envs/rdqn/lib/python3.11/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/smorad/miniforge3/envs/rdqn/lib/python3.11/copy.py", line 271, in _reconstruct
    state = deepcopy(state, memo)
            ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/smorad/miniforge3/envs/rdqn/lib/python3.11/copy.py", line 146, in deepcopy
    y = copier(x, memo)
        ^^^^^^^^^^^^^^^
  File "/Users/smorad/miniforge3/envs/rdqn/lib/python3.11/copy.py", line 231, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
                             ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/smorad/miniforge3/envs/rdqn/lib/python3.11/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/smorad/miniforge3/envs/rdqn/lib/python3.11/copy.py", line 297, in _reconstruct
    value = deepcopy(value, memo)
            ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/smorad/miniforge3/envs/rdqn/lib/python3.11/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/smorad/miniforge3/envs/rdqn/lib/python3.11/copy.py", line 271, in _reconstruct
    state = deepcopy(state, memo)
            ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/smorad/miniforge3/envs/rdqn/lib/python3.11/copy.py", line 146, in deepcopy
    y = copier(x, memo)
        ^^^^^^^^^^^^^^^
  File "/Users/smorad/miniforge3/envs/rdqn/lib/python3.11/copy.py", line 231, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
                             ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/smorad/miniforge3/envs/rdqn/lib/python3.11/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/smorad/miniforge3/envs/rdqn/lib/python3.11/copy.py", line 297, in _reconstruct
    value = deepcopy(value, memo)
            ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/smorad/miniforge3/envs/rdqn/lib/python3.11/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/smorad/miniforge3/envs/rdqn/lib/python3.11/copy.py", line 271, in _reconstruct
    state = deepcopy(state, memo)
            ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/smorad/miniforge3/envs/rdqn/lib/python3.11/copy.py", line 146, in deepcopy
    y = copier(x, memo)
        ^^^^^^^^^^^^^^^
  File "/Users/smorad/miniforge3/envs/rdqn/lib/python3.11/copy.py", line 231, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
                             ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/smorad/miniforge3/envs/rdqn/lib/python3.11/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/smorad/miniforge3/envs/rdqn/lib/python3.11/copy.py", line 271, in _reconstruct
    state = deepcopy(state, memo)
            ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/smorad/miniforge3/envs/rdqn/lib/python3.11/copy.py", line 146, in deepcopy
    y = copier(x, memo)
        ^^^^^^^^^^^^^^^
  File "/Users/smorad/miniforge3/envs/rdqn/lib/python3.11/copy.py", line 231, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
                             ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/smorad/miniforge3/envs/rdqn/lib/python3.11/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/smorad/miniforge3/envs/rdqn/lib/python3.11/copy.py", line 297, in _reconstruct
    value = deepcopy(value, memo)
            ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/smorad/miniforge3/envs/rdqn/lib/python3.11/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/smorad/miniforge3/envs/rdqn/lib/python3.11/copy.py", line 271, in _reconstruct
    state = deepcopy(state, memo)
            ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/smorad/miniforge3/envs/rdqn/lib/python3.11/copy.py", line 146, in deepcopy
    y = copier(x, memo)
        ^^^^^^^^^^^^^^^
  File "/Users/smorad/miniforge3/envs/rdqn/lib/python3.11/copy.py", line 231, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
                             ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/smorad/miniforge3/envs/rdqn/lib/python3.11/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/smorad/miniforge3/envs/rdqn/lib/python3.11/copy.py", line 297, in _reconstruct
    value = deepcopy(value, memo)
            ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/smorad/miniforge3/envs/rdqn/lib/python3.11/copy.py", line 153, in deepcopy
    y = copier(memo)
        ^^^^^^^^^^^^
  File "/Users/smorad/miniforge3/envs/rdqn/lib/python3.11/site-packages/torch/_tensor.py", line 86, in __deepcopy__
    raise RuntimeError(
RuntimeError: Only Tensors created explicitly by the user (graph leaves) support the deepcopy protocol at the moment
Exception ignored in: <function TensorDictBase.__del__ at 0x11ca4b600>
Traceback (most recent call last):
  File "/Users/smorad/code/from_src/tensordict/tensordict/tensordict.py", line 3563, in __del__
    for td in self._locked_tensordicts:
              ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'TensorDict' object has no attribute '_locked_tensordicts'
Exception ignored in: <function TensorDictBase.__del__ at 0x11ca4b600>
Traceback (most recent call last):
  File "/Users/smorad/code/from_src/tensordict/tensordict/tensordict.py", line 3563, in __del__
    for td in self._locked_tensordicts:
              ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'TensorDict' object has no attribute '_locked_tensordicts'
```

## Checklist

- [x] I have checked that there is no similar issue in the repo (**required**)
- [x] I have read the [documentation](https://github.com/pytorch/rl/tree/main/docs/) (**required**)
- [x] I have provided a minimal working example to reproduce the bug (**required**)

**Comment by vmoens** [comment]
Got it
Let's see if these will fix it
https://github.com/pytorch/rl/pull/1424
https://github.com/pytorch-labs/tensordict/pull/508

**Comment by smorad** [comment]
> Got it
> Let's see if these will fix it
> #1424
> [pytorch-labs/tensordict#508](https://github.com/pytorch-labs/tensordict/pull/508)

Yup, that did it! Thanks.
