### ISSUE TITLE
[BUG] error in coding_dqn.py 

### ISSUE THREAD

**Issue by davidenitti** [pytorch/rl#1516]
## Describe the bug
I have an error in coding_dqn.py 
```
/usr/bin/python3.10 /home/davide/PycharmProjects/RL/tutorials/sphinx-tutorials/coding_dqn.py 
state dict of the observation norm: OrderedDict([('standard_normal', tensor(True, device='cuda:0')), ('loc', tensor([[[0.9895]],

        [[0.9895]],

        [[0.9895]],

        [[0.9895]]], device='cuda:0')), ('scale', tensor([[[0.0737]],

        [[0.0737]],

        [[0.0737]],

        [[0.0737]]], device='cuda:0'))])
state dict of the observation norm: OrderedDict([('standard_normal', tensor(True, device='cuda:0')), ('loc', tensor([[[0.9895]],

        [[0.9895]],

        [[0.9895]],

        [[0.9895]]], device='cuda:0')), ('scale', tensor([[[0.0737]],

        [[0.0737]],

        [[0.0737]],

        [[0.0737]]], device='cuda:0'))])
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.10/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/usr/lib/python3.10/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/usr/lib/python3.10/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/usr/lib/python3.10/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/usr/lib/python3.10/runpy.py", line 289, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/usr/lib/python3.10/runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/davide/PycharmProjects/RL/tutorials/sphinx-tutorials/coding_dqn.py", line 568, in <module>
    collector = get_collector(
  File "/home/davide/PycharmProjects/RL/tutorials/sphinx-tutorials/coding_dqn.py", line 400, in get_collector
    data_collector = MultiaSyncDataCollector(
  File "/usr/local/lib/python3.10/dist-packages/torchrl/collectors/collectors.py", line 1746, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torchrl/collectors/collectors.py", line 1216, in __init__
    self._run_processes()
  File "/usr/local/lib/python3.10/dist-packages/torchrl/collectors/collectors.py", line 1273, in _run_processes
    proc.start()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/usr/lib/python3.10/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/usr/lib/python3.10/multiprocessing/context.py", line 288, in _Popen
    return Popen(process_obj)
  File "/usr/lib/python3.10/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/usr/lib/python3.10/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/usr/lib/python3.10/multiprocessing/popen_spawn_posix.py", line 42, in _launch
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "/usr/lib/python3.10/multiprocessing/spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "/usr/lib/python3.10/multiprocessing/spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
Traceback (most recent call last):
  File "/home/davide/PycharmProjects/RL/tutorials/sphinx-tutorials/coding_dqn.py", line 568, in <module>
    collector = get_collector(
  File "/home/davide/PycharmProjects/RL/tutorials/sphinx-tutorials/coding_dqn.py", line 400, in get_collector
    data_collector = MultiaSyncDataCollector(
  File "/usr/local/lib/python3.10/dist-packages/torchrl/collectors/collectors.py", line 1746, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torchrl/collectors/collectors.py", line 1216, in __init__
    self._run_processes()
  File "/usr/local/lib/python3.10/dist-packages/torchrl/collectors/collectors.py", line 1288, in _run_processes
    msg = pipe_parent.recv()
  File "/usr/lib/python3.10/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib/python3.10/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.10/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
[W CudaIPCTypes.cpp:15] Producer process has been terminated before all shared CUDA tensors released. See Note [Sharing CUDA tensors]

```

if I disable the parallel, with 1 worker and collector I get
```

Traceback (most recent call last):
  File "/home/davide/PycharmProjects/RL/tutorials/sphinx-tutorials/coding_dqn.py", line 568, in <module>
    collector = get_collector(
  File "/home/davide/PycharmProjects/RL/tutorials/sphinx-tutorials/coding_dqn.py", line 400, in get_collector
    data_collector = MultiaSyncDataCollector(
  File "/usr/local/lib/python3.10/dist-packages/torchrl/collectors/collectors.py", line 1746, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torchrl/collectors/collectors.py", line 1216, in __init__
    self._run_processes()
  File "/usr/local/lib/python3.10/dist-packages/torchrl/collectors/collectors.py", line 1273, in _run_processes
    proc.start()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/usr/lib/python3.10/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/usr/lib/python3.10/multiprocessing/context.py", line 288, in _Popen
    return Popen(process_obj)
  File "/usr/lib/python3.10/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/usr/lib/python3.10/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/usr/lib/python3.10/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/usr/lib/python3.10/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: cannot pickle 'pygame.Surface' object
```

**Comment by vmoens** [comment]
Hello! Thanks for reporting this.
Regarding the first part, I think the error comes from the fact that we don't decorate our tutorials within a `if __name__ == "__main__":` which will allow you to run multiple workers in parallel.
The second may require a bit more knowledge about what you're doing. Which env is it? How did you proceed to reduce the number of workers to 1?

**Comment by vmoens** [comment]
Any update on this? Have you tried to execute your code with the `if __name__ == "__main__"` decorator?

**Comment by Thomberger** [comment]
By executing the code with the decorator the error disappear.

However a other error appear when running the file with he gpu.
Apparently the input to the DQN is not on the correct device, how to correct that ?

When running the file with device = "cpu", the file is correctly executed to the end.



```
"C:/Users/Thomas Berger/.conda/envs/Reinforce/python.exe" "c:/Users/Thomas Berger/Documents\RL\tutorials\sphinx-tutorials\coding_dqn.py "
state dict of the observation norm: OrderedDict([('standard_normal', tensor(True, device='cuda:0')), ('loc', tensor([[[0.9895]],

        [[0.9895]],

        [[0.9895]],

        [[0.9895]]], device='cuda:0')), ('scale', tensor([[[0.0737]],

        [[0.0737]],

        [[0.0737]],

        [[0.0737]]], device='cuda:0'))])
self.log_dir: C:\Users\THOMAS~1\AppData\Local\Temp\tmp3k77k1mu\dqn_exp_6b88456a-6cd8-11ee-925c-dc2148bdc9e5
  0%|                                                                                                                                                                             | 0/5000 [00:00<?, ?it/s]Traceback (most recent call last):
  File "C:\Users\Thomas Berger\.conda\envs\Reinforce\lib\site-packages\tensordict\nn\common.py", line 1178, in forward
    raise err
  File "C:\Users\Thomas Berger\.conda\envs\Reinforce\lib\site-packages\tensordict\nn\common.py", line 1164, in forward
    tensors = self._call_module(tensors, **kwargs)
  File "C:\Users\Thomas Berger\.conda\envs\Reinforce\lib\site-packages\tensordict\nn\common.py", line 1121, in _call_module
    out = self.module(*tensors, **kwargs)
  File "C:\Users\Thomas Berger\.conda\envs\Reinforce\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\Thomas Berger\.conda\envs\Reinforce\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl        
    return forward_call(*args, **kwargs)
  File "C:\Users\Thomas Berger\.conda\envs\Reinforce\lib\site-packages\tensordict\nn\functional_modules.py", line 588, in new_fun   
    return getattr(type(self), fun_name)(self, *args, **kwargs)
  File "C:\Users\Thomas Berger\.conda\envs\Reinforce\lib\site-packages\torchrl\modules\models\models.py", line 865, in forward      
    x = self.features(x)
  File "C:\Users\Thomas Berger\.conda\envs\Reinforce\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\Thomas Berger\.conda\envs\Reinforce\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl        
    return forward_call(*args, **kwargs)
  File "C:\Users\Thomas Berger\.conda\envs\Reinforce\lib\site-packages\tensordict\nn\functional_modules.py", line 588, in new_fun   
    return getattr(type(self), fun_name)(self, *args, **kwargs)
  File "C:\Users\Thomas Berger\.conda\envs\Reinforce\lib\site-packages\torchrl\modules\models\models.py", line 484, in forward
    out = super(ConvNet, self).forward(inputs)
  File "C:\Users\Thomas Berger\.conda\envs\Reinforce\lib\site-packages\torch\nn\modules\container.py", line 215, in forward
    input = module(input)
  File "C:\Users\Thomas Berger\.conda\envs\Reinforce\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\Thomas Berger\.conda\envs\Reinforce\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\Thomas Berger\.conda\envs\Reinforce\lib\site-packages\tensordict\nn\functional_modules.py", line 588, in new_fun
    return getattr(type(self), fun_name)(self, *args, **kwargs)
  File "C:\Users\Thomas Berger\.conda\envs\Reinforce\lib\site-packages\torch\nn\modules\conv.py", line 460, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "C:\Users\Thomas Berger\.conda\envs\Reinforce\lib\site-packages\torch\nn\modules\conv.py", line 456, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
  File "C:\Users\Thomas Berger\.conda\envs\Reinforce\lib\site-packages\tensordict\memmap.py", line 431, in __torch_function__
    ret = func(*args, **kwargs)
RuntimeError: Input type (torch.FloatTensor) and weight type (torch.cuda.FloatTensor) should be the same or input should be a MKLDNN tensor and weight is a dense tensor

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\Thomas Berger\Documents\RL\tutorials\sphinx-tutorials\coding_dqn.py ", line 662, in <module>
    trainer.train()
  File "C:\Users\Thomas Berger\.conda\envs\Reinforce\lib\site-packages\torchrl\trainers\trainers.py", line 451, in train
    self.optim_steps(batch)
  File "C:\Users\Thomas Berger\.conda\envs\Reinforce\lib\site-packages\torchrl\trainers\trainers.py", line 484, in optim_steps
    losses_td = self.loss_module(sub_batch)
  File "C:\Users\Thomas Berger\.conda\envs\Reinforce\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\Thomas Berger\.conda\envs\Reinforce\lib\site-packages\torch\nn\modules\module.py", line 1568, in _call_impl
    result = forward_call(*args, **kwargs)
  File "C:\Users\Thomas Berger\.conda\envs\Reinforce\lib\site-packages\tensordict\_contextlib.py", line 126, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\Thomas Berger\.conda\envs\Reinforce\lib\site-packages\tensordict\nn\common.py", line 282, in wrapper
    return func(_self, tensordict, *args, **kwargs)
  File "C:\Users\Thomas Berger\.conda\envs\Reinforce\lib\site-packages\torchrl\objectives\dqn.py", line 292, in forward
    self.value_network(
  File "C:\Users\Thomas Berger\.conda\envs\Reinforce\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\Thomas Berger\.conda\envs\Reinforce\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\Thomas Berger\.conda\envs\Reinforce\lib\site-packages\tensordict\nn\functional_modules.py", line 576, in new_fun
    out = getattr(type(self), fun_name)(self, *args, **kwargs)
  File "C:\Users\Thomas Berger\.conda\envs\Reinforce\lib\site-packages\tensordict\nn\common.py", line 282, in wrapper
    return func(_self, tensordict, *args, **kwargs)
  File "C:\Users\Thomas Berger\.conda\envs\Reinforce\lib\site-packages\tensordict\_contextlib.py", line 126, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\Thomas Berger\.conda\envs\Reinforce\lib\site-packages\tensordict\nn\utils.py", line 254, in wrapper
    return func(_self, tensordict, *args, **kwargs)
  File "C:\Users\Thomas Berger\.conda\envs\Reinforce\lib\site-packages\tensordict\nn\sequence.py", line 426, in forward
    tensordict = self._run_module(module, tensordict, **kwargs)
  File "C:\Users\Thomas Berger\.conda\envs\Reinforce\lib\site-packages\tensordict\nn\sequence.py", line 407, in _run_module
    tensordict = module(tensordict, **kwargs)
  File "C:\Users\Thomas Berger\.conda\envs\Reinforce\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\Thomas Berger\.conda\envs\Reinforce\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\Thomas Berger\.conda\envs\Reinforce\lib\site-packages\tensordict\nn\functional_modules.py", line 588, in new_fun
    return getattr(type(self), fun_name)(self, *args, **kwargs)
  File "C:\Users\Thomas Berger\.conda\envs\Reinforce\lib\site-packages\tensordict\nn\common.py", line 282, in wrapper
    return func(_self, tensordict, *args, **kwargs)
  File "C:\Users\Thomas Berger\.conda\envs\Reinforce\lib\site-packages\tensordict\_contextlib.py", line 126, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\Thomas Berger\.conda\envs\Reinforce\lib\site-packages\tensordict\nn\utils.py", line 254, in wrapper
    return func(_self, tensordict, *args, **kwargs)
  File "C:\Users\Thomas Berger\.conda\envs\Reinforce\lib\site-packages\tensordict\nn\common.py", line 1204, in forward
    raise RuntimeError(
RuntimeError: TensorDictModule failed with operation
    DuelingCnnDQNet(
      (features): ConvNet(
        (0): Conv2d(4, 32, kernel_size=(6, 6), stride=(2, 2))
        (1): ELU(alpha=1.0)
        (2): Conv2d(32, 64, kernel_size=(4, 4), stride=(2, 2))
        (3): ELU(alpha=1.0)
        (4): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1))
        (5): ELU(alpha=1.0)
        (6): SquashDims()
      )
      (advantage): MLP(
        (0): Linear(in_features=9216, out_features=64, bias=True)
        (1): ELU(alpha=1.0)
        (2): Linear(in_features=64, out_features=64, bias=True)
        (3): ELU(alpha=1.0)
        (4): Linear(in_features=64, out_features=2, bias=True)
      )
      (value): MLP(
        (0): Linear(in_features=9216, out_features=64, bias=True)
        (1): ELU(alpha=1.0)
        (2): Linear(in_features=64, out_features=64, bias=True)
        (3): ELU(alpha=1.0)
        (4): Linear(in_features=64, out_features=1, bias=True)
      )
    )
    in_keys=['pixels']
    out_keys=['action_value'].
```

**Comment by Thomberger** [comment]
The problem was the device implemented by the `ReplayBufferTrainer` line number 608 from the original file `coding_dqn.py`.

The original line 
```buffer_hook = ReplayBufferTrainer(
    get_replay_buffer(buffer_size, n_optim, batch_size=batch_size),
    flatten_tensordicts=True,
)
```

should include the device as an argument:

```buffer_hook = ReplayBufferTrainer(
    get_replay_buffer(buffer_size, n_optim, batch_size=batch_size),
    flatten_tensordicts=True,
    device=device
)
```

With that the file correctly run.
