### ISSUE TITLE
[BUG] cannot import name 'MemoryMappedTensor' from 'tensordict.memmap' on local installation

### ISSUE THREAD

**Issue by iamreadyi** [pytorch/rl#1734]
## Describe the bug

I have a conda env and pytorch nightly version 2.2.0.dev20231204 in it.

I try to install torchrl nightly to Silicon Mac. I git clone the repo, install it with the command python setup.py develop. On installation I get errors about Deprecated config in `setup.cfg` which i will append end of the text as INSTALL ERROR .

 In this case I cannot import torchrl and get this error message:

```bash
(nightly) xyz@xyzs-MacBook-Air ~ % python -c "import torchrl"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/xyz/rl/torchrl/__init__.py", line 38, in <module>
    import torchrl.collectors
  File "/Users/xyz/rl/torchrl/collectors/__init__.py", line 6, in <module>
    from .collectors import (
  File "/Users/xyz/rl/torchrl/collectors/collectors.py", line 42, in <module>
    from torchrl.data.tensor_specs import CompositeSpec, TensorSpec
  File "/Users/xyz/rl/torchrl/data/__init__.py", line 6, in <module>
    from . import datasets
  File "/Users/xyz/rl/torchrl/data/datasets/__init__.py", line 1, in <module>
    from .d4rl import D4RLExperienceReplay
  File "/Users/xyz/rl/torchrl/data/datasets/d4rl.py", line 27, in <module>
    from torchrl.data.replay_buffers import TensorDictReplayBuffer
  File "/Users/xyz/rl/torchrl/data/replay_buffers/__init__.py", line 6, in <module>
    from .replay_buffers import (
  File "/Users/xyz/rl/torchrl/data/replay_buffers/replay_buffers.py", line 25, in <module>
    from torchrl.data.replay_buffers.samplers import (
  File "/Users/xyz/rl/torchrl/data/replay_buffers/samplers.py", line 25, in <module>
    from .storages import Storage
  File "/Users/xyz/rl/torchrl/data/replay_buffers/storages.py", line 16, in <module>
    from tensordict.memmap import MemmapTensor, MemoryMappedTensor
ImportError: cannot import name 'MemoryMappedTensor' from 'tensordict.memmap' (/Users/xyz/miniforge3/envs/nightly/lib/python3.9/site-packages/tensordict/memmap.py)

```
According to internet calling setup.py directly is being deprecated, as [explained here](https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html#summary).

I git clone the repo, install it with the command pip install . and get Successfully installed torchrl-0.2.1+841f8d9. 

This time also get another error similar but about C++ extensions while trying to import:

```bash
(nightly) xyz@xyzs-MacBook-Air ~ % python -c "import torchrl"
/Users/xyz/rl/torchrl/_extension.py:24: UserWarning: torchrl C++ extension is not available.
  warnings.warn("torchrl C++ extension is not available.")
/Users/xyz/rl/torchrl/data/replay_buffers/samplers.py:23: UserWarning: Failed to import torchrl C++ binaries. Some modules (eg, prioritized replay buffers) may not work with your installation. If you installed TorchRL from PyPI, please report the bug on TorchRL github. If you installed TorchRL locally and/or in development mode, check that you have all the required compiling packages.
  warnings.warn(EXTENSION_WARNING)
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/xyz/rl/torchrl/__init__.py", line 38, in <module>
    import torchrl.collectors
  File "/Users/xyz/rl/torchrl/collectors/__init__.py", line 6, in <module>
    from .collectors import (
  File "/Users/xyz/rl/torchrl/collectors/collectors.py", line 42, in <module>
    from torchrl.data.tensor_specs import CompositeSpec, TensorSpec
  File "/Users/xyz/rl/torchrl/data/__init__.py", line 6, in <module>
    from . import datasets
  File "/Users/xyz/rl/torchrl/data/datasets/__init__.py", line 1, in <module>
    from .d4rl import D4RLExperienceReplay
  File "/Users/xyz/rl/torchrl/data/datasets/d4rl.py", line 27, in <module>
    from torchrl.data.replay_buffers import TensorDictReplayBuffer
  File "/Users/xyz/rl/torchrl/data/replay_buffers/__init__.py", line 6, in <module>
    from .replay_buffers import (
  File "/Users/xyz/rl/torchrl/data/replay_buffers/replay_buffers.py", line 25, in <module>
    from torchrl.data.replay_buffers.samplers import (
  File "/Users/xyz/rl/torchrl/data/replay_buffers/samplers.py", line 25, in <module>
    from .storages import Storage
  File "/Users/xyz/rl/torchrl/data/replay_buffers/storages.py", line 16, in <module>
    from tensordict.memmap import MemmapTensor, MemoryMappedTensor
ImportError: cannot import name 'MemoryMappedTensor' from 'tensordict.memmap' (/Users/xyz/miniforge3/envs/nightly/lib/python3.9/site-packages/tensordict/memmap.py)
```
I tried the directions in readme of torchrl under Troubleshooting. It didn't work with any combination that i tried.
INSTALL ERROR

```bash
(nightly) xyz@xyzs-MacBook-Air rl % python setup.py develop   
Building wheel torchrl-0.2.1+841f8d9
BUILD_VERSION is None
-- PyTorch dependency: torch>=2.1.0
/Users/xyz/miniforge3/envs/nightly/lib/python3.9/site-packages/setuptools/config/setupcfg.py:293: _DeprecatedConfig: Deprecated config in `setup.cfg`
!!

        ********************************************************************************
        The license_file parameter is deprecated, use license_files instead.

        This deprecation is overdue, please update your project and remove deprecated
        calls to avoid build errors in the future.

        See https://setuptools.pypa.io/en/latest/userguide/declarative_config.html for details.
        ********************************************************************************

!!
  parsed = self.parsers.get(option_name, lambda x: x)(value)
running develop
/Users/xyz/miniforge3/envs/nightly/lib/python3.9/site-packages/setuptools/command/develop.py:40: EasyInstallDeprecationWarning: easy_install command is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` and ``easy_install``.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://github.com/pypa/setuptools/issues/917 for details.
        ********************************************************************************

!!
  easy_install.initialize_options(self)
/Users/xyz/miniforge3/envs/nightly/lib/python3.9/site-packages/setuptools/_distutils/cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` directly.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
        ********************************************************************************

!!
  self.initialize_options()
running egg_info
writing torchrl.egg-info/PKG-INFO
writing dependency_links to torchrl.egg-info/dependency_links.txt
writing requirements to torchrl.egg-info/requires.txt
writing top-level names to torchrl.egg-info/top_level.txt
reading manifest file 'torchrl.egg-info/SOURCES.txt'
adding license file 'LICENSE'
writing manifest file 'torchrl.egg-info/SOURCES.txt'
running build_ext
building 'torchrl._torchrl' extension
Emitting ninja build file /Users/xyz/rl/build/temp.macosx-11.0-arm64-cpython-39/build.ninja...
Compiling objects...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: no work to do.
clang++ -bundle -undefined dynamic_lookup -Wl,-rpath,/Users/xyz/miniforge3/envs/nightly/lib -L/Users/xyz/miniforge3/envs/nightly/lib -Wl,-rpath,/Users/xyz/miniforge3/envs/nightly/lib -L/Users/xyz/miniforge3/envs/nightly/lib /Users/xyz/rl/build/temp.macosx-11.0-arm64-cpython-39/Users/xyz/rl/torchrl/csrc/pybind.o -L/Users/xyz/miniforge3/envs/nightly/lib/python3.9/site-packages/torch/lib -lc10 -ltorch -ltorch_cpu -ltorch_python -o build/lib.macosx-11.0-arm64-cpython-39/torchrl/_torchrl.so
ld: warning: object file (/Users/xyz/rl/build/temp.macosx-11.0-arm64-cpython-39/Users/xyz/rl/torchrl/csrc/pybind.o) was built for newer macOS version (13.0) than being linked (11.0)
copying build/lib.macosx-11.0-arm64-cpython-39/torchrl/_torchrl.so -> torchrl
Creating /Users/xyz/miniforge3/envs/nightly/lib/python3.9/site-packages/torchrl.egg-link (link to .)
torchrl 0.2.1+841f8d9 is already the active version in easy-install.pth

Installed /Users/xyz/rl
Processing dependencies for torchrl==0.2.1+841f8d9
Searching for tensordict>=0.2.0
Reading https://pypi.org/simple/tensordict/
Downloading https://files.pythonhosted.org/packages/b7/1e/71104a3c278e035ff028ebb9f0845b4278eb956f1bbd42f4be89620facbd/tensordict-0.2.1-cp39-cp39-macosx_11_0_arm64.whl#sha256=b386a983fa7cc7ce4a0eb6f145aae39f24ae605f2dbc66eccbc228b1fcd9a461
Best match: tensordict 0.2.1
Processing tensordict-0.2.1-cp39-cp39-macosx_11_0_arm64.whl
removing '/Users/xyz/miniforge3/envs/nightly/lib/python3.9/site-packages/tensordict-0.2.1-py3.9-macosx-11.0-arm64.egg' (and everything under it)
Installing tensordict-0.2.1-cp39-cp39-macosx_11_0_arm64.whl to /Users/xyz/miniforge3/envs/nightly/lib/python3.9/site-packages
Adding tensordict 0.2.1 to easy-install.pth file

Installed /Users/xyz/miniforge3/envs/nightly/lib/python3.9/site-packages/tensordict-0.2.1-py3.9-macosx-11.0-arm64.egg
Searching for cloudpickle==3.0.0
Best match: cloudpickle 3.0.0
Processing cloudpickle-3.0.0-py3.9.egg
Adding cloudpickle 3.0.0 to easy-install.pth file

Using /Users/xyz/miniforge3/envs/nightly/lib/python3.9/site-packages/cloudpickle-3.0.0-py3.9.egg
Searching for packaging==23.2
Best match: packaging 23.2
Processing packaging-23.2-py3.9.egg
Adding packaging 23.2 to easy-install.pth file

Using /Users/xyz/miniforge3/envs/nightly/lib/python3.9/site-packages/packaging-23.2-py3.9.egg
Searching for numpy==1.26.2
Best match: numpy 1.26.2
Adding numpy 1.26.2 to easy-install.pth file
Installing f2py script to /Users/xyz/miniforge3/envs/nightly/bin

Using /Users/xyz/miniforge3/envs/nightly/lib/python3.9/site-packages
Searching for torch==2.2.0.dev20231204
Best match: torch 2.2.0.dev20231204
Adding torch 2.2.0.dev20231204 to easy-install.pth file
Installing convert-caffe2-to-onnx script to /Users/xyz/miniforge3/envs/nightly/bin
Installing convert-onnx-to-caffe2 script to /Users/xyz/miniforge3/envs/nightly/bin
Installing torchrun script to /Users/xyz/miniforge3/envs/nightly/bin

Using /Users/xyz/miniforge3/envs/nightly/lib/python3.9/site-packages
Searching for fsspec==2023.12.0
Best match: fsspec 2023.12.0
Processing fsspec-2023.12.0-py3.9.egg
Adding fsspec 2023.12.0 to easy-install.pth file

Using /Users/xyz/miniforge3/envs/nightly/lib/python3.9/site-packages/fsspec-2023.12.0-py3.9.egg
Searching for Jinja2==3.1.2
Best match: Jinja2 3.1.2
Adding Jinja2 3.1.2 to easy-install.pth file

Using /Users/xyz/miniforge3/envs/nightly/lib/python3.9/site-packages
Searching for networkx==3.2.1
Best match: networkx 3.2.1
Adding networkx 3.2.1 to easy-install.pth file

Using /Users/xyz/miniforge3/envs/nightly/lib/python3.9/site-packages
Searching for sympy==1.12
Best match: sympy 1.12
Adding sympy 1.12 to easy-install.pth file
Installing isympy script to /Users/xyz/miniforge3/envs/nightly/bin

Using /Users/xyz/miniforge3/envs/nightly/lib/python3.9/site-packages
Searching for typing-extensions==4.8.0
Best match: typing-extensions 4.8.0
Adding typing-extensions 4.8.0 to easy-install.pth file

Using /Users/xyz/miniforge3/envs/nightly/lib/python3.9/site-packages
Searching for filelock==3.13.1
Best match: filelock 3.13.1
Adding filelock 3.13.1 to easy-install.pth file

Using /Users/xyz/miniforge3/envs/nightly/lib/python3.9/site-packages
Searching for MarkupSafe==2.1.3
Best match: MarkupSafe 2.1.3
Adding MarkupSafe 2.1.3 to easy-install.pth file

Using /Users/xyz/miniforge3/envs/nightly/lib/python3.9/site-packages
Searching for mpmath==1.3.0
Best match: mpmath 1.3.0
Adding mpmath 1.3.0 to easy-install.pth file

Using /Users/xyz/miniforge3/envs/nightly/lib/python3.9/site-packages
Finished processing dependencies for torchrl==0.2.1+841f8d9
```

**Comment by vmoens** [comment]
> According to internet calling setup.py directly is being deprecated, as [explained here](https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html#summary).

That is true but it is not actively deprecated and all pytorch libraries (as well as others) still rely on that for local development (as alternatives such as `pip install -e .` do not fully work)

```
   File "/Users/xyz/rl/torchrl/data/replay_buffers/storages.py", line 16, in <module>
    from tensordict.memmap import MemmapTensor, MemoryMappedTensor
ImportError: cannot import name 'MemoryMappedTensor' from 'tensordict.memmap' 
(/Users/xyz/miniforge3/envs/nightly/lib/python3.9/site-packages/tensordict/memmap.py)
```

The most likely explanation is that you have installed the latest stable release of tensordict and not the nightly (or the cloned version like you would do with torchrl using `python setup.py install`)

**Comment by iamreadyi** [comment]
Thank you it is solved. Installing torchrl nightly in silicon m2 mac.
