### ISSUE TITLE
[BUG] Can't sample from TensorDictReplayBuffer with CatFrames transform

### ISSUE THREAD

**Issue by dtch1997** [pytorch/rl#1761]
## Describe the bug

Standard pixel transforms don't work as expected with TensorDictReplayBuffer

## To Reproduce

Here's a minimal working example taken from the documentation of [CatFrames](https://pytorch.org/rl/reference/generated/torchrl.envs.transforms.CatFrames.html). 

```python
import torchrl
from torchrl.envs import GymEnv, TransformedEnv

from torchrl.envs import (
    ToTensorImage,
    Resize,
    UnsqueezeTransform,
    CatFrames,
    Compose,
)

from torchrl.data import LazyMemmapStorage
from torchrl.data import TensorDictReplayBuffer

from torchrl.collectors import SyncDataCollector, RandomPolicy

if __name__ == "__main__":

    env = GymEnv("CartPole-v1", from_pixels=True, pixels_only=False, device="cpu")
    env = TransformedEnv(
        env, 
        transform=Compose(
            ToTensorImage(in_keys=["pixels"], out_keys=["pixels_transformed"]),
            Resize(in_keys = ["pixels_transformed"], out_keys=["pixels_transformed"], h = 96, w = 96),
            UnsqueezeTransform(unsqueeze_dim=-4, in_keys=["pixels_transformed"]),
            CatFrames(N=4, dim=-4, in_keys=["pixels_transformed"]),
        )                 
    )

    collector = SyncDataCollector(
        env,
        RandomPolicy(env.action_spec),
        frames_per_batch=10,
        total_frames=10,
    )
    for data in collector:
        break

    t = Compose(
        ToTensorImage(in_keys=["pixels", ("next", "pixels")], out_keys=["pixels_transformed", ("next", "pixels_transformed")]),
        Resize(in_keys=["pixels_transformed", ("next", "pixels_transformed")], w=96, h=96),
        CatFrames(dim=-4, N=4, in_keys=["pixels_transformed", ("next", "pixels_transformed")]),
    )

    rb = TensorDictReplayBuffer(
        storage = LazyMemmapStorage(100),
        batch_size=10,
        transform = t
    )

    data_exclude = data.exclude("pixels_transformed", ("next", "pixels_transformed"), "collector")
    rb.add(data_exclude) 
    s = rb.sample()
```

This results in: 

```bash
Traceback (most recent call last):                                                                                                                                                                              
  File "/home/daniel/lavid/.venv/lib/python3.10/site-packages/tensordict/tensordict.py", line 1815, in as_tensor                                                                                                
    return self._fast_apply(lambda x: x.as_tensor())                                                                                                                                                            
  File "/home/daniel/lavid/.venv/lib/python3.10/site-packages/tensordict/tensordict.py", line 1668, in _fast_apply                                                                                              
    return self._apply_nest(                                                                                                                                                                                    
  File "/home/daniel/lavid/.venv/lib/python3.10/site-packages/tensordict/tensordict.py", line 1633, in _apply_nest
    item_trsf = fn(item, *_others)
  File "/home/daniel/lavid/.venv/lib/python3.10/site-packages/tensordict/tensordict.py", line 1815, in <lambda>
    return self._fast_apply(lambda x: x.as_tensor()) 
AttributeError: 'Tensor' object has no attribute 'as_tensor'. Did you mean: 'new_tensor'?

```

## Expected behavior

The example provided in documentation works as expected

## System info

Describe the characteristic of your environment:
 *  `torchrl==0.2.1`
 * `tensordict==0.2.1`
 * `python == 3.10.13`

## Additional context

If we instead do: 
```python
rb.extend(data_exclude)
s = rb.sample()
```

Then there is no error, but we get an annoying warning every time we sample:
```
UserWarning: The last dimension of the tensordict should be marked as 'time'. CatFrames will unfold the data along the time dimension assuming that the time dimension is the last dimension of the input tensordict. Define a 'time' dimension name (e.g., `tensordict.refine_names(..., 'time')`) to skip this warning.
```

This is the workaround I'm using at the moment, but it's very annoying because it interrupts my `tqdm` progress bar with endless warnings

## Reason and Possible fixes

If you know or suspect the reason for this bug, paste the code lines and suggest modifications.

## Checklist

- [x] I have checked that there is no similar issue in the repo (**required**)
- [x] I have read the [documentation](https://github.com/pytorch/rl/tree/main/docs/) (**required**)
- [x] I have provided a minimal working example to reproduce the bug (**required**)

**Comment by vmoens** [comment]
Thanks for pointing this out
This has been fixed in the nightlies and will be part of the next release!
In the meantime you can call 
```
    rb = TensorDictReplayBuffer(
        storage = LazyMemmapStorage(100),
        batch_size=10,
        transform = t,
        collate_fn=lambda x: x.clone(),
    )
```
