### ISSUE TITLE
[BUG?] Batch dimension mismatch in a custom env

### ISSUE THREAD

**Issue by islijepcevic** [pytorch/rl#1766]
I'm trying to create my own environment, and keep getting dimension mismatch for batch dimension. Failure happens within `env.fake_tensordict()`, which is often called by the framework (e.g. by Collectors). 

Minimal example:
```python
class MiniEnv(EnvBase):
    def __init__(self):
        super().__init__()

        # e.g. a conveyor belt with some values there
        observation_spec = DiscreteTensorSpec(n=3, shape=torch.Size([6]))
        self.observation_spec = CompositeSpec(
            observation=observation_spec, shape=observation_spec.shape
        )
        self.action_spec = OneHotDiscreteTensorSpec(
            2,  # shift left or right
            shape=torch.Size([2]),
        )
        self.reward_spec = UnboundedContinuousTensorSpec(shape=torch.Size([1]))

    def _reset(self, tensordict, *kwargs):
        pass

    def _step(self, tensordict):
        pass

    def _set_seed(self, seed):
        pass

env = MiniEnv()
env.fake_tensordict()
```

This creates error:
```shell
Traceback (most recent call last):
  File "/Users/user/anaconda3/envs/torchrl/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/user/anaconda3/envs/torchrl/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/user/projects/kaggle/santa23/environments/mini_env.py", line 38, in <module>
    env.fake_tensordict()
  File "/Users/user/anaconda3/envs/torchrl/lib/python3.9/site-packages/torchrl/envs/common.py", line 2107, in fake_tensordict
    next_output.update(fake_reward)
  File "/Users/user/anaconda3/envs/torchrl/lib/python3.9/site-packages/tensordict/tensordict.py", line 1883, in update
    self.set(key, value, inplace=inplace)
  File "/Users/user/anaconda3/envs/torchrl/lib/python3.9/site-packages/tensordict/tensordict.py", line 911, in set
    return self._set_tuple(key, item, inplace=inplace, validated=False)
  File "/Users/user/anaconda3/envs/torchrl/lib/python3.9/site-packages/tensordict/tensordict.py", line 4494, in _set_tuple
    return self._set_str(key[0], value, inplace=inplace, validated=validated)
  File "/Users/user/anaconda3/envs/torchrl/lib/python3.9/site-packages/tensordict/tensordict.py", line 4465, in _set_str
    value = self._validate_value(value, check_shape=True)
  File "/Users/user/anaconda3/envs/torchrl/lib/python3.9/site-packages/tensordict/tensordict.py", line 2020, in _validate_value
RuntimeError: batch dimension mismatch, got self.batch_size=torch.Size([6]) and value.shape[:self.batch_dims]=torch.Size([1]) with value tensor([0.])
```

Equivalent error happens if in my specs, I provide unsqueezed shapes (such as `torch.Size([1, N])` or even `torch.Size([*self.batch_size, N])`).
It seems that calling `*spec.zero()` creates a `TensorDict` where batch_size is the whole shape from the `spec`. Is there a way to avoid that?

### System info

Python 3.9.18
torch 2.1.2  (installed via conda)
macOS Sonoma 14.2.1 on M2 macbook pro
torchrl 0.2.1 (installed via pip)
tensordict 0.2.1 (dependency of torchrl)

**Comment by vmoens** [comment]
The error comes from the fact that your observation spec has the same shape as its leaf:
```python
        self.observation_spec = CompositeSpec(
            observation=observation_spec, shape=observation_spec.shape
        )
```
The `observation_spec` shape should be the same as the environment batch size:
```python
        self.observation_spec = CompositeSpec(
            observation=observation_spec, shape=[]
        )
```

You should think of the shape of the `CompositeSpec` as the batch-size, and the shape of the observation_spec leaf as a shape made of `[*batch_size, *feature_size]`.

Hope that helps!
