### ISSUE TITLE
[BUG] ImportError: cannot import name 'MemoryMappedTensor' from 'tensordict'

### ISSUE THREAD

**Issue by Cadene** [pytorch/rl#1797]
## Describe the bug

After clean install, importing torchrl gets an import error
```
python -c "import torchrl"
ImportError: cannot import name 'MemoryMappedTensor' from 'tensordict'
```

## To Reproduce

```bash
conda create --name torch_rl_311 python=3.11
conda activate torch_rl_311
pip install torchrl
python -c "import torchrl"

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/rcadene/code/rl/torchrl/__init__.py", line 38, in <module>
    import torchrl.collectors
  File "/home/rcadene/code/rl/torchrl/collectors/__init__.py", line 6, in <module>
    from .collectors import (
  File "/home/rcadene/code/rl/torchrl/collectors/collectors.py", line 42, in <module>
    from torchrl.data.tensor_specs import CompositeSpec, TensorSpec
  File "/home/rcadene/code/rl/torchrl/data/__init__.py", line 6, in <module>
    from . import datasets
  File "/home/rcadene/code/rl/torchrl/data/datasets/__init__.py", line 1, in <module>
    from .d4rl import D4RLExperienceReplay
  File "/home/rcadene/code/rl/torchrl/data/datasets/d4rl.py", line 29, in <module>
    from torchrl.data.replay_buffers.replay_buffers import TensorDictReplayBuffer
  File "/home/rcadene/code/rl/torchrl/data/replay_buffers/__init__.py", line 6, in <module>
    from .replay_buffers import (
  File "/home/rcadene/code/rl/torchrl/data/replay_buffers/replay_buffers.py", line 31, in <module>
    from torchrl.data.replay_buffers.samplers import (
  File "/home/rcadene/code/rl/torchrl/data/replay_buffers/samplers.py", line 19, in <module>
    from tensordict import MemoryMappedTensor, TensorDict
ImportError: cannot import name 'MemoryMappedTensor' from 'tensordict' (/home/rcadene/miniconda3/envs/torch_rl_311/lib/python3.11/site-packages/tensordict/__init__.py)
```

## System info

```bash
cat /proc/version
Linux version 6.5.0-4-amd64 (debian-kernel@lists.debian.org) (gcc-13 (Debian 13.2.0-6) 13.2.0, GNU ld (GNU Binutils for Debian) 2.41) #1 SMP PREEMPT_DYNAMIC Debian 6.5.10-1 (2023-11-03)
```

```python
import sys
print(sys.version, sys.platform)
3.11.7 (main, Dec 15 2023, 18:12:31) [GCC 11.2.0] linux
```

```python
import tensordict
tensordict.__version__
'0.2.1'
```

## Reason and Possible fixes

tensordict version is not compatible with torchrl. But it's weird to me why the stable torchrl version is not compatible. I thought this should be part of an integration test.

Thanks for your help!

## Checklist

- [X] I have checked that there is no similar issue in the repo (**required**)
- [X] I have read the [documentation](https://github.com/pytorch/rl/tree/main/docs/) (**required**)
- [X] I have provided a minimal working example to reproduce the bug (**required**)

**Comment by Cadene** [comment]
Fixed, by installing development version of tensordict. Still gets a weird warning about failing to import C++ binaries:
```
pip uninstall tensordict
git clone https://github.com/pytorch/tensordict.git
cd tensordict
python setup.py develop
python -c "import tensordict;print(tensordict.__version__)"
0.3.0+3f977c6

python -c "import torchrl"
/home/rcadene/code/rl/torchrl/data/replay_buffers/samplers.py:36: UserWarning: Failed to import torchrl C++ binaries. Some modules (eg, prioritized replay buffers) may not work with your installation. If you installed TorchRL from PyPI, please report the bug on TorchRL github. If you installed TorchRL locally and/or in development mode, check that you have all the required compiling packages.
  warnings.warn(EXTENSION_WARNING)
```

**Comment by Cadene** [comment]
There was an issue with my PYTHONPATH.

Fixed, by resetting:
```
export PYTHONPATH=""
```
