### ISSUE TITLE
[BUG?] How to handle next with custom environment and check_env_specs()

### ISSUE THREAD

**Issue by mneilly** [pytorch/rl#2052]
I recently starting learning TorchRL so it's possible that this is a misunderstanding on my part and not an actual bug.

## Describe the bug

I'm trying to setup a simple spatial arrangement problem using a custom environment. There are N blocks each with an x, y position and a size. My action consists of a block index and x and y deltas. The observation spec is setup to hold the updated positions and sizes of the blocks. The action spec is setup to hold the index and delta. For now, reward is just the distance from center for each block so the network is only trying to learn to move blocks to the center of the space. For state, I include distance from center.

When check_env_specs() is run it fails indicating that the real tensor contains the next state but the fake tensor does not.

>.venv/lib/python3.11/site-packages/torchrl/envs/utils.py:160: UserWarning: The expected key set and actual key set differ. This will work but with a slower thr$
Actual - Expected keys={('next', 'state', 'distance_from_center')}.
  warnings.warn(
Traceback (most recent call last):
  File "spatial-arrangement/mwe.py", line 115, in <module>
    check_env_specs(env)
  File ".venv/lib/python3.11/site-packages/torchrl/envs/utils.py", line 634, in check_env_specs
    raise AssertionError(
AssertionError: The keys of the specs and data do not match:
    - List of keys present in real but not in fake: {('next', 'state', 'distance_from_center')},
    - List of keys present in fake but not in real: set().

 
`check_env_specs` calls `env.fake_tensordict()` to create `fake_tensordict` whose keys are later compared to `real_tensordict` with keys obtained from a rollout. Unless "next" is explicitly added the key check will not pass because the created fake_tensordict will only contain observation, reward and done but not next. 

https://github.com/pytorch/rl/blob/cd540bf96a9c998e89a59382b1961fd8a2bc57f0/torchrl/envs/common.py#L2840-L2845

## To Reproduce

The following is an MWE that shows the failure.

```python
import torch
from torchrl.envs import EnvBase
from torchrl.envs.utils import check_env_specs
from torchrl.data import BoundedTensorSpec, CompositeSpec, UnboundedContinuousTensorSpec
from tensordict import TensorDict


NUM_BLOCKS = 4

class BlockArrangementEnv(EnvBase):

    def __init__(self):
        super().__init__()

        self.observation_spec = CompositeSpec({
            "observation": CompositeSpec({
                "positions": BoundedTensorSpec(
                    low=0.0,
                    high=1.0,
                    shape=torch.Size([NUM_BLOCKS, 2]),
                    dtype=torch.float32
                ),
                "sizes": BoundedTensorSpec(
                    low=0.1,
                    high=1.0,
                    shape=torch.Size([NUM_BLOCKS, 2]),
                dtype=torch.float32
                )
            }),
        })

        self.state_spec = CompositeSpec({
            "state": CompositeSpec({
                "distance_from_center": UnboundedContinuousTensorSpec(
                    shape=torch.Size([NUM_BLOCKS]),
                    dtype=torch.float32
                ),
            })
        })

        self.action_spec = CompositeSpec({
            "action": CompositeSpec({
                "index": BoundedTensorSpec(
                    low=0,
                    high=NUM_BLOCKS - 1,
                    shape=torch.Size([1]),
                    dtype=torch.int
                ),
                "delta": BoundedTensorSpec(
                    low=-1.0,
                    high=1.0,
                    shape=torch.Size([2]),
                    dtype=torch.float32
                )
            })
        })

        self.reward_spec = UnboundedContinuousTensorSpec(
            shape=torch.Size([NUM_BLOCKS]),
            dtype=torch.float32
        )


    def _reset(self, td):
        return TensorDict({
            "observation": {
                "positions": torch.rand([NUM_BLOCKS, 2]),
                "sizes": torch.FloatTensor(NUM_BLOCKS, 2).uniform_(0.1, 1.0),
            },
            "state": {
                "distance_from_center": torch.rand([NUM_BLOCKS]),
            }
        }, batch_size=[])

    def _step(self, td, **kwargs):
        return TensorDict({
            "observation": {
                "positions": torch.rand([NUM_BLOCKS, 2]),
                "sizes": torch.FloatTensor(NUM_BLOCKS, 2).uniform_(0.1, 1.0),
            },
            "state": {
                "distance_from_center": torch.rand([NUM_BLOCKS]),
            },
            "reward": torch.rand([NUM_BLOCKS]),
            "done": torch.tensor(False)
        }, batch_size=[])

    def _set_seed(self, seed):
        pass


env = BlockArrangementEnv()
check_env_specs(env)
```

## Expected behavior

I'm not expecting that I need to add next explicitly anywhere since it seems like something that should be derived.

## Screenshots

Not applicable

## System info

Everything installed in a virtualenv with pip.

torchrl version:  2024.3.13 
numpy version:  1.26.4 
sys version:  3.11.8 (main, Feb  7 2024, 21:52:08) [GCC 13.2.0] 
sys platform:  linux

## Additional context

No additional context

## Reason and Possible fixes

When the fake tensordict is created, neither state nor action are added.

```python
    def fake_tensordict(self) -> TensorDictBase:
        ...
        fake_obs = observation_spec.zero()
        ...
        next_output = fake_obs.clone()
        next_output.update(fake_reward)
        next_output.update(fake_done)
        fake_in_out.update(fake_done.clone())
        if "next" not in fake_in_out.keys():
            fake_in_out.set("next", next_output)
        else:
            fake_in_out.get("next").update(next_output)

        fake_in_out.batch_size = self.batch_size
        fake_in_out = fake_in_out.to(self.device)
        return fake_in_out
```

## Checklist

- [x] I have checked that there is no similar issue in the repo (**required**)
- [x] I have read the [documentation](https://github.com/pytorch/rl/tree/main/docs/) (**required**)
- [x] I have provided a minimal working example to reproduce the bug (**required**)

**Comment by vmoens** [comment]
Since your state is also in the observation I think you should just add it to your observation specs:
```python
        self.observation_spec = CompositeSpec({
            "observation": CompositeSpec({
                "positions": BoundedTensorSpec(
                    low=0.0,
                    high=1.0,
                    shape=torch.Size([NUM_BLOCKS, 2]),
                    dtype=torch.float32
                ),
                "sizes": BoundedTensorSpec(
                    low=0.1,
                    high=1.0,
                    shape=torch.Size([NUM_BLOCKS, 2]),
                dtype=torch.float32
                )
            }),
            "state": CompositeSpec({
                "distance_from_center": UnboundedContinuousTensorSpec(
                    shape=torch.Size([NUM_BLOCKS]),
                    dtype=torch.float32
                ),
            }),
        })
```

The reason we don't do it automatically is that you could have a state that is at the root (not in "next") and copied at every call of `step_mdp` (carried on unchanged throughout the rollout). 
Here is an example using your code:


```python
import torch
from torchrl.envs import EnvBase
from torchrl.envs.utils import check_env_specs
from torchrl.data import BoundedTensorSpec, CompositeSpec, UnboundedContinuousTensorSpec
from tensordict import TensorDict

COUNTER = 0
NUM_BLOCKS = 4

class BlockArrangementEnv(EnvBase):

    def __init__(self):
        super().__init__()

        self.observation_spec = CompositeSpec({
            "observation": CompositeSpec({
                "positions": BoundedTensorSpec(
                    low=0.0,
                    high=1.0,
                    shape=torch.Size([NUM_BLOCKS, 2]),
                    dtype=torch.float32
                ),
                "sizes": BoundedTensorSpec(
                    low=0.1,
                    high=1.0,
                    shape=torch.Size([NUM_BLOCKS, 2]),
                dtype=torch.float32
                )
            }),
            "state": CompositeSpec({
                "distance_from_center": UnboundedContinuousTensorSpec(
                    shape=torch.Size([NUM_BLOCKS]),
                    dtype=torch.float32
                ),
            }),
        })

        self.full_state_spec = CompositeSpec({
            "state": CompositeSpec({
                "distance_from_center": UnboundedContinuousTensorSpec(
                    shape=torch.Size([NUM_BLOCKS]),
                    dtype=torch.float32
                ),
            }),
            "context": UnboundedContinuousTensorSpec(
                    shape=torch.Size([NUM_BLOCKS]),
                    dtype=torch.float32
                )
        })

        self.action_spec = CompositeSpec({
            "action": CompositeSpec({
                "index": BoundedTensorSpec(
                    low=0,
                    high=NUM_BLOCKS - 1,
                    shape=torch.Size([1]),
                    dtype=torch.int
                ),
                "delta": BoundedTensorSpec(
                    low=-1.0,
                    high=1.0,
                    shape=torch.Size([2]),
                    dtype=torch.float32
                )
            })
        })

        self.reward_spec = UnboundedContinuousTensorSpec(
            shape=torch.Size([NUM_BLOCKS]),
            dtype=torch.float32
        )


    def _reset(self, td):
        global COUNTER
        COUNTER += 1
        return TensorDict({
            "observation": {
                "positions": torch.rand([NUM_BLOCKS, 2]),
                "sizes": torch.FloatTensor(NUM_BLOCKS, 2).uniform_(0.1, 1.0),
            },
            "state": {
                "distance_from_center": torch.rand([NUM_BLOCKS]),
            },
            "context": self.full_state_spec["context"].zero() + COUNTER,
        }, batch_size=[])

    def _step(self, td, **kwargs):
        return TensorDict({
            "observation": {
                "positions": torch.rand([NUM_BLOCKS, 2]),
                "sizes": torch.FloatTensor(NUM_BLOCKS, 2).uniform_(0.1, 1.0),
            },
            "state": {
                "distance_from_center": torch.rand([NUM_BLOCKS]),
            },
            "reward": torch.rand([NUM_BLOCKS]),
            "done": torch.tensor(False)
        }, batch_size=[])

    def _set_seed(self, seed):
        pass


env = BlockArrangementEnv()
check_env_specs(env)
assert (env.rollout(3)["context"] == COUNTER).all()
```

**Comment by mneilly** [comment]
Ah, thanks, that makes sense and there's no compelling reason for me to have distance_from_center as separate state for this case other than to learn how the mechanisms work for observation and state.
