### ISSUE TITLE
[BUG] `empty_net_` in `MultiAgentNetBase` seemingly interferes with `MultiSyncDataCollector`

### ISSUE THREAD

**Issue by N00bcak** [pytorch/rl#2180]
## Describe the bug

With a policy instantiated from `MultiAgentNetBase` subclass, I am unable to use `MultiSyncDataCollector` to obtain transitions for my algorithm.

## To Reproduce
 A minimal example:
```python
from torchrl.envs import PettingZooEnv, ParallelEnv, SerialEnv
from torchrl.collectors import SyncDataCollector, MultiSyncDataCollector, RandomPolicy

from torchrl.modules.models.multiagent import MultiAgentMLP
if __name__ == "__main__":

    def base_env_fn():
        return PettingZooEnv(
            task = "multiwalker_v9",
            parallel = True,
            seed = 42,
            n_walkers = 3,
            shared_reward = False,
            max_cycles = 1000,
            render_mode = None,
            device = "cpu",
        )

    collector = MultiSyncDataCollector(
        [base_env_fn for _ in range(4)],
        policy = MultiAgentMLP(31, 4, 3, centralised = True, share_params = True),#RandomPolicy(action_spec = base_env_fn().action_spec, action_key=("walker", "action")),
        frames_per_batch = 100,
        max_frames_per_traj = 50,
        total_frames = 200,
        device = "cpu",
        reset_at_each_iter = False,
    )
    try:
        for i, tensordict in enumerate(collector):
            print("Reached")
    finally:
        collector.shutdown()
```

```bash
Traceback (most recent call last):
  File "/home/n00bcak/Desktop/<path_to_script>/script.py", line 32, in <module>
    collector = MultiSyncDataCollector(
  File "/home/n00bcak/Desktop/<path_to_venv>/site-packages/torchrl/collectors/collectors.py", line 1514, in __init__
    self._run_processes()
  File "/home/n00bcak/Desktop/<path_to_venv>/site-packages/torchrl/collectors/collectors.py", line 1672, in _run_processes
    proc.start()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/usr/lib/python3.10/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/usr/lib/python3.10/multiprocessing/context.py", line 288, in _Popen
    return Popen(process_obj)
  File "/usr/lib/python3.10/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/usr/lib/python3.10/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/usr/lib/python3.10/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/usr/lib/python3.10/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
  File "/home/n00bcak/Desktop/<path_to_venv>/site-packages/torch/multiprocessing/reductions.py", line 569, in reduce_storage
    fd, size = storage._share_fd_cpu_()
  File "/home/n00bcak/Desktop/<path_to_venv>/site-packages/torch/storage.py", line 304, in wrapper
    return fn(self, *args, **kwargs)
  File "/home/n00bcak/Desktop/<path_to_venv>/site-packages/torch/storage.py", line 374, in _share_fd_cpu_
    return super()._share_fd_cpu_(*args, **kwargs)
RuntimeError: _share_fd_: only available on CPU
```

## Expected behavior

Collector iterator is exhausted and program exits normally.

## System info
```python
>>> import torchrl, numpy, sys
>>> print(f"TorchRL: {torchrl.__version__}\nNumPy: {numpy.__version__}\nPython3 Ver: {sys.version}\nPlatform: {sys.platform}")
TorchRL: 0.4.0 
NumPy: 1.25.0 
Python3 Ver: 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0] 
Platform: linux
```
```bash
> lsb_release -a
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.3 LTS
Release:	22.04
Codename:	jammy
```

## Additional context

This issue is related to #2179.

See [the postscripts of this post](https://discuss.pytorch.org/t/pettingzoo-trouble-running-multiple-marl-environments-in-parallel/203706/).

## Cause of bug
`empty_net_` is initialized as a "meta"-tensor (with the "meta" device).
https://github.com/pytorch/rl/blob/0f02c4a62533e37ed984f5e788410aaf253de91f/torchrl/modules/models/multiagent.py#L57

Therefore, it cannot be shared to other processes like a CPU tensor could be.

## Suggested Fix
**Have the `MultiAgentNetBase` constructor accept a boolean flag to disable initialization of `_empty_net` as a "meta"-tensor**
```python
class MultiAgentNetBase(nn.Module):
    """A base class for multi-agent networks."""

    _empty_net: nn.Module

    def __init__(
        self,
        *,
        n_agents: int,
        centralised: bool,
        share_params: bool,
        agent_dim: int,
        vmap_randomness: str = "different",
        empty_net_not_meta: bool = False, # <- suggested new flag 
        **kwargs,
    ):
    ...
```
As in #2179, a caveat to this suggestion is my inexperience with TorchRL.

However, since `empty_net_` seems like something meant simply to be filled in with `self.params`:
https://github.com/pytorch/rl/blob/0f02c4a62533e37ed984f5e788410aaf253de91f/torchrl/modules/models/multiagent.py#L69-L73

whatever memory costs could be incurred by initializing `_empty_net` as a CPU tensor should be outweighed by the benefits of being able to collect transitions from multiple environments.

## Checklist

- [x] I have checked that there is no similar issue in the repo (**required**)
- [x] I have read the [documentation](https://github.com/pytorch/rl/tree/main/docs/) (**required**)
- [x] I have provided a minimal working example to reproduce the bug (**required**)

**Comment by vmoens** [comment]
We're about to fix sharing "meta" tensors across processes, which I think will resolve this issue.

cc @albanD @mikaylagawarecki

**Comment by kurtamohler** [comment]
This is working now with the nightly build of pytorch.

The code snippet from the issue has a small mistake--`MultiSyncDataCollector`'s `policy` argument does not accept a `MultiAgentMLP` directly, so I had to wrap it in an appropriate `TensorDictModule`. The following now runs without error on my local checkout:

```python
from torchrl.envs import PettingZooEnv
from torchrl.collectors import MultiSyncDataCollector
from tensordict.nn import TensorDictModule
from torchrl.modules.models.multiagent import MultiAgentMLP

if __name__ == "__main__":
    def base_env_fn():
        return PettingZooEnv(
            task = "multiwalker_v9",
            parallel = True,
            seed = 42, 
            n_walkers = 3,
            shared_reward = False,
            max_cycles = 1000,
            render_mode = None,
            device = "cpu",
        )

    module = MultiAgentMLP(31, 4, 3, centralised=True, share_params=True)
    policy = TensorDictModule(
        module,
        out_keys=[('walker', 'action')],
        in_keys=[('walker', 'observation')],
    )   

    collector = MultiSyncDataCollector(
        [base_env_fn for _ in range(4)],
        policy = policy,
        frames_per_batch = 100,
        max_frames_per_traj = 50, 
        total_frames = 200,
        device = "cpu",
        reset_at_each_iter = False,
    )   
    try:
        for i, tensordict in enumerate(collector):
            print("Reached")
    finally:
        collector.shutdown()
```
