### ISSUE TITLE
[BUG] ParallelEnv + MeltingPot

### ISSUE THREAD

**Issue by jduquevan** [pytorch/rl#2277]
## Describe the bug

Meltingpot integration with ParallelEnv fails.

## To Reproduce

```
from torchrl.envs.libs.meltingpot import MeltingpotEnv
from torchrl.envs import ParallelEnv

env = ParallelEnv(6, MeltingpotEnv("commons_harvest__open"))
obs = env.reset()
```

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mila/j/juan.duque/anaconda3/envs/meltingpot/lib/python3.11/site-packages/torchrl/envs/common.py", line 2120, in reset
    tensordict_reset = self._reset(tensordict, **kwargs)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mila/j/juan.duque/anaconda3/envs/meltingpot/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/mila/j/juan.duque/anaconda3/envs/meltingpot/lib/python3.11/site-packages/torchrl/envs/batched_envs.py", line 56, in decorated_fun
    self._start_workers()
  File "/home/mila/j/juan.duque/anaconda3/envs/meltingpot/lib/python3.11/site-packages/torchrl/envs/batched_envs.py", line 1275, in _start_workers
    process.start()
  File "/home/mila/j/juan.duque/anaconda3/envs/meltingpot/lib/python3.11/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
                  ^^^^^^^^^^^^^^^^^
  File "/home/mila/j/juan.duque/anaconda3/envs/meltingpot/lib/python3.11/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mila/j/juan.duque/anaconda3/envs/meltingpot/lib/python3.11/multiprocessing/context.py", line 288, in _Popen
    return Popen(process_obj)
           ^^^^^^^^^^^^^^^^^^
  File "/home/mila/j/juan.duque/anaconda3/envs/meltingpot/lib/python3.11/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/home/mila/j/juan.duque/anaconda3/envs/meltingpot/lib/python3.11/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/home/mila/j/juan.duque/anaconda3/envs/meltingpot/lib/python3.11/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/home/mila/j/juan.duque/anaconda3/envs/meltingpot/lib/python3.11/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
  File "/home/mila/j/juan.duque/anaconda3/envs/meltingpot/lib/python3.11/site-packages/torchrl/data/utils.py", line 241, in __getstate__
    return cloudpickle.dumps((self.fn, self.kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mila/j/juan.duque/anaconda3/envs/meltingpot/lib/python3.11/site-packages/cloudpickle/cloudpickle.py", line 1479, in dumps
    cp.dump(obj)
  File "/home/mila/j/juan.duque/anaconda3/envs/meltingpot/lib/python3.11/site-packages/cloudpickle/cloudpickle.py", line 1245, in dump
    return super().dump(obj)
           ^^^^^^^^^^^^^^^^^
TypeError: cannot pickle 'dmlab2d.dmlab2d_pybind.Lab2d' object
```

## Expected behavior

The env.reset() call should return a dictionary object that contains the observations for each environment in the batch.

## System info

Describe the characteristic of your environment:
 * Describe how the library was installed (pip, source, ...)
 * Python version
 * Versions of any other relevant libraries

```python
>>>import torchrl, numpy, sys
>>>print(torchrl.__version__, numpy.__version__, sys.version, sys.platform)
>>>2024.4.25 1.26.4 3.11.9 (main, Apr 19 2024, 16:48:06) [GCC 11.2.0] linux

conda list

dm-meltingpot             2.3.1                    pypi_0    pypi
numpy                     1.26.4                   pypi_0    pypi
python                    3.11.9               h955ad1f_0  
tensordict-nightly        2024.4.24                pypi_0    pypi
torch                     2.3.1                    pypi_0    pypi
torchrl-nightly           2024.4.25                pypi_0    pypi
     


```

## Checklist

- [Yes ] I have checked that there is no similar issue in the repo (**required**)
- [Yes ] I have read the [documentation](https://github.com/pytorch/rl/tree/main/docs/) (**required**)
- [Yes ] I have provided a minimal working example to reproduce the bug (**required**)

**Comment by vmoens** [comment]
Hello

Try this:
```python
from torchrl.envs.libs.meltingpot import MeltingpotEnv
from torchrl.envs import ParallelEnv

env = ParallelEnv(6, lambda: MeltingpotEnv("commons_harvest__open"))
obs = env.reset()
```
This is the very reason we ask to pass builders and not objects in ParallelEnv!

**Comment by jduquevan** [comment]
Thank you, this worked!
