### ISSUE TITLE
can't run any scenario

### ISSUE THREAD

**Issue by majid5776** [pytorch/rl#2299]
Hello. why this error happened when I want to run this script: python mappo_ippo.py --m env.scenario_name=balance
## Describe the bug

Traceback (most recent call last):
  File "mappo_ippo.py", line 123, in train
    collector = SyncDataCollector(
  File "D:\RL\MARL\MARL\lib\site-packages\torchrl\collectors\collectors.py", line 703, in __init__
    policy_output = self.policy(policy_input)
  File "D:\RL\MARL\MARL\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\RL\MARL\MARL\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\RL\MARL\MARL\lib\site-packages\tensordict\nn\common.py", line 289, in wrapper
    return func(_self, tensordict, *args, **kwargs)
  File "D:\RL\MARL\MARL\lib\site-packages\tensordict\_contextlib.py", line 126, in decorate_context
    return func(*args, **kwargs)
  File "D:\RL\MARL\MARL\lib\site-packages\tensordict\nn\utils.py", line 261, in wrapper
    return func(_self, tensordict, *args, **kwargs)
  File "D:\RL\MARL\MARL\lib\site-packages\tensordict\nn\probabilistic.py", line 577, in forward
    return self.module[-1](tensordict_out, _requires_sample=self._requires_sample)
  File "D:\RL\MARL\MARL\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\RL\MARL\MARL\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\RL\MARL\MARL\lib\site-packages\tensordict\nn\common.py", line 289, in wrapper
    return func(_self, tensordict, *args, **kwargs)
  File "D:\RL\MARL\MARL\lib\site-packages\tensordict\_contextlib.py", line 126, in decorate_context
    return func(*args, **kwargs)
  File "D:\RL\MARL\MARL\lib\site-packages\tensordict\nn\utils.py", line 261, in wrapper
    return func(_self, tensordict, *args, **kwargs)
  File "D:\RL\MARL\MARL\lib\site-packages\tensordict\nn\probabilistic.py", line 390, in forward
    dist = self.get_dist(tensordict)
  File "D:\RL\MARL\MARL\lib\site-packages\tensordict\nn\probabilistic.py", line 349, in get_dist
    raise TypeError(
TypeError: distribution keywords and tensordict keys indicated by ProbabilisticTensorDictModule.dist_keys must match.Got this error message:
    __init__() got an unexpected keyword argument 'low'
with dist_keys=[('agents', 'loc'), ('agents', 'scale')]

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

**Comment by vmoens** [comment]
Can you share your setup (torchrl, pytorch and tensordict) versions?

**Comment by majid5776** [comment]
torch: 2.3.1
torchrl: 0.4.0
tensordict: 0.4.0

**Comment by vmoens** [comment]
I think it's because you're running the examples on main but they've been updated with the low/high entries in the examples.
You can upgrade to nightlies or alternatively use the examples from the 0.4 tag
https://github.com/pytorch/rl/tree/v0.4.0

**Comment by majid5776** [comment]
thanks.
another question:
I've design my custom navigation env that have obstacles on it and the agents don't hit each other.
when I run my mappo_ippo.py I got strange outputs. can my model overfitted?
my custom_env is:
https://drive.google.com/file/d/1yw1rOpJcmoU99zcz-2wEGqV_ZnfOT1qF/view?usp=sharing
my config of mappo_ippo is:
max_steps:200
n_iters:625
n_agents and n_targets:3
backend:csv
entropy_eps:0.0001
remain confs is the same.

when I look at my csv and my videos they are surprising:
in my video the 20 first epochs they reach the goals very easy but after that episode they stop.
in my csv the train_mean_reward increasing non-stoply but my critic loss also increasing.
is this meaning my model overfitted?

**Comment by majid5776** [comment]
@vmoens
