### ISSUE TITLE
[BUG]TypeError: __init__() got an unexpected keyword argument 'disable_env_checker'

### ISSUE THREAD

**Issue by neuronphysics** [pytorch/rl#689]
I used your library on google colab and it works without a problem. However, after spending a day to install gym in ubuntu using conda and run torchrl code, I am getting this error:

```
>>> from torchrl.envs.libs.gym import _has_gym, GymEnv, GymWrapper
>>> env_torchrl = GymEnv("InvertedPendulum-v2")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/anaconda3/lib/python3.9/site-packages/torchrl/envs/libs/gym.py", line 282, in __init__
    super().__init__(**kwargs)
  File "/home/anaconda3/lib/python3.9/site-packages/torchrl/envs/libs/gym.py", line 149, in __init__
    super().__init__(**kwargs)
  File "/home/anaconda3/lib/python3.9/site-packages/torchrl/envs/common.py", line 717, in __init__
    self._env = self._build_env(**kwargs)  # writes the self._env attribute
  File "/home/anaconda3/lib/python3.9/site-packages/torchrl/envs/libs/gym.py", line 327, in _build_env
    raise err
  File "/home/anaconda3/lib/python3.9/site-packages/torchrl/envs/libs/gym.py", line 313, in _build_env
    env = self.lib.make(env_name, **kwargs)
  File "/home/anaconda3/lib/python3.9/site-packages/gym/envs/registration.py", line 235, in make
    return registry.make(id, **kwargs)
  File "/home/anaconda3/lib/python3.9/site-packages/gym/envs/registration.py", line 129, in make
    env = spec.make(**kwargs)
  File "/home/anaconda3/lib/python3.9/site-packages/gym/envs/registration.py", line 90, in make
    env = cls(**_kwargs)
TypeError: __init__() got an unexpected keyword argument 'disable_env_checker'

``` 
Why did this error occur?

**Comment by neuronphysics** [comment]
@vmoens Thanks for the reply. The gym version that I have is `gym.__version__ '0.21.0'`

**Comment by vmoens** [comment]
The new wheels should solve this issue. Let me know if it doesn't, happy to re-open then.

**Comment by neuronphysics** [comment]
Hello,
I was able to install torchrl in the jupyter notebook locally and run it. However, when I tried to re-run my previous code in google colab I am getting the following error:
```
     54 get_ipython().system('pip3 install torchrl')
---> 55 import torchrl
     56 #https://github.com/pytorch/rl
     57 from torchrl.envs.libs.gym import _has_gym, GymEnv, GymWrapper

7 frames
[/usr/local/lib/python3.7/dist-packages/torchrl/__init__.py](https://localhost:8080/#) in <module>
     33 
     34 
---> 35 import torchrl.collectors
     36 import torchrl.data
     37 import torchrl.envs

[/usr/local/lib/python3.7/dist-packages/torchrl/collectors/__init__.py](https://localhost:8080/#) in <module>
      4 # LICENSE file in the root directory of this source tree.
      5 
----> 6 from .collectors import (
      7     SyncDataCollector,
      8     aSyncDataCollector,

[/usr/local/lib/python3.7/dist-packages/torchrl/collectors/collectors.py](https://localhost:8080/#) in <module>
     22 from torch.utils.data import IterableDataset
     23 
---> 24 from torchrl.envs.transforms import TransformedEnv
     25 from torchrl.envs.utils import set_exploration_mode, step_mdp
     26 from .._utils import _check_for_faulty_process, prod

[/usr/local/lib/python3.7/dist-packages/torchrl/envs/__init__.py](https://localhost:8080/#) in <module>
      4 # LICENSE file in the root directory of this source tree.
      5 
----> 6 from .common import Specs, make_tensordict, EnvBase, EnvMetaData
      7 from .env_creator import EnvCreator, get_env_metadata
      8 from .gym_like import GymLikeEnv, default_info_dict_reader

[/usr/local/lib/python3.7/dist-packages/torchrl/envs/common.py](https://localhost:8080/#) in <module>
     16 from tensordict.tensordict import TensorDictBase, TensorDict
     17 
---> 18 from torchrl.data import CompositeSpec, TensorSpec
     19 from .._utils import seed_generator, prod
     20 from ..data.utils import DEVICE_TYPING

[/usr/local/lib/python3.7/dist-packages/torchrl/data/__init__.py](https://localhost:8080/#) in <module>
      5 
      6 from .postprocs import MultiStep
----> 7 from .replay_buffers import (
      8     ReplayBuffer,
      9     PrioritizedReplayBuffer,

[/usr/local/lib/python3.7/dist-packages/torchrl/data/replay_buffers/__init__.py](https://localhost:8080/#) in <module>
      4 # LICENSE file in the root directory of this source tree.
      5 
----> 6 from .replay_buffers import (
      7     ReplayBuffer,
      8     PrioritizedReplayBuffer,

[/usr/local/lib/python3.7/dist-packages/torchrl/data/replay_buffers/replay_buffers.py](https://localhost:8080/#) in <module>
     18 from torch import Tensor
     19 
---> 20 from torchrl._torchrl import (
     21     MinSegmentTreeFp32,
     22     MinSegmentTreeFp64,

ImportError: /usr/local/lib/python3.7/dist-packages/torchrl/_torchrl.so: undefined symbol: _ZN8pybind116detail11type_casterIN2at6TensorEvE4loadENS_6handleEb
```
Any idea why I am getting this new error?

**Comment by vmoens** [comment]
Unfortunately this is a [known issue](#619), our cp37 wheels do not work across all python 3.7 binaries.
In the meantime, you can execute 
```
!pip install "git+https://github.com/pytorch/rl@0.0.3"
```

**Comment by vmoens** [comment]
Are you sure the package has been reinstalled? Maybe try 
```
!pip install "git+https://github.com/pytorch/rl --force-reinstall"
```

**Comment by vmoens** [comment]
I managed to install the lib and make it work
There's still a warning from vision, I guess they have a similar issue with python 3.7?

**Comment by neuronphysics** [comment]
Thank you so much. YES, it works now.
