### ISSUE TITLE
[BUG] MultOneHotDiscreteTensorSpec.is_in raise a RuntimeError when input is not a one hot tensor 

### ISSUE THREAD

**Issue by riiswa** [pytorch/rl#815]
## Describe the bug

MultOneHotDiscreteTensorSpec.is_in raise a RuntimeError when input is not a one hot tensor.

```python
# The input is tensor([[0, 1, 0],
#        [0, 0, 1],
#      [3, 0, 1]])
test/test_tensor_spec.py:310 (test_multi_discrete_conversion[device0-shape0-ns1])
Traceback (most recent call last):
  File "/Users/waris/Projects/rl/test/test_tensor_spec.py", line 338, in test_multi_discrete_conversion
    assert one_hot.is_in(categorical.to_onehot(categorical.rand(shape)))
  File "/Users/waris/Projects/rl/torchrl/data/tensor_specs.py", line 909, in is_in
    vals = self._split(val)
  File "/Users/waris/Projects/rl/torchrl/data/tensor_specs.py", line 882, in _split
    vals = val.split([space.n for space in self.space], dim=-1)
  File "/Users/waris/Projects/rl/venv/lib/python3.10/site-packages/torch/_tensor.py", line 789, in split
    return torch._VF.split_with_sizes(self, split_size, dim)
RuntimeError: split_with_sizes expects split_sizes to sum exactly to 3 (input tensor's size at dimension -1), but got split_sizes=[5, 2, 3]
```

## Expected behavior

Should return `False` instead raising an error. 

**NOTE**: In general when we test method that return boolean, we should also write tests for the `False` case.

## Checklist

- [x] I have checked that there is no similar issue in the repo (**required**)
- [x] I have read the [documentation](https://github.com/pytorch/rl/tree/main/docs/) (**required**)
- [x] I have provided a minimal working example to reproduce the bug (**required**)

**Comment by vmoens** [comment]
Good catch
Is there a clever way of doing this or should we just capture the error and return False in that case?

**Comment by vmoens** [comment]
> NOTE: In general when we test method that return boolean, we should also write tests for the False case.

hehe, indeed :)

**Comment by riiswa** [comment]
> Good catch Is there a clever way of doing this or should we just capture the error and return False in that case?

I'm gonna work on a simple and clever way of doing it, because exception handling can lead to performance issue.
