### ISSUE TITLE
[BUG] ImportError / is this lib compatible with win10?

### ISSUE THREAD

**Issue by anonymouscnuser** [pytorch/rl#997]
## Describe the bug

seems `_torchrl` not found
```
from torchrl._torchrl import (
    MinSegmentTreeFp32,
    MinSegmentTreeFp64,
    SumSegmentTreeFp32,
    SumSegmentTreeFp64,
)
```
## To Reproduce

`python -c "import torchrl"`

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\anaconda\envs\easyrl\lib\site-packages\torchrl\__init__.py", line 35, in <module>
    import torchrl.collectors
  File "D:\anaconda\envs\easyrl\lib\site-packages\torchrl\collectors\__init__.py", line 6, in <module>
    from .collectors import (
  File "D:\anaconda\envs\easyrl\lib\site-packages\torchrl\collectors\collectors.py", line 24, in <module>
    from torchrl.envs.transforms import TransformedEnv
  File "D:\anaconda\envs\easyrl\lib\site-packages\torchrl\envs\__init__.py", line 6, in <module>
    from .common import Specs, make_tensordict, EnvBase, EnvMetaData
  File "D:\anaconda\envs\easyrl\lib\site-packages\torchrl\envs\common.py", line 18, in <module>
    from torchrl.data import CompositeSpec, TensorSpec
  File "D:\anaconda\envs\easyrl\lib\site-packages\torchrl\data\__init__.py", line 7, in <module>
    from .replay_buffers import (
  File "D:\anaconda\envs\easyrl\lib\site-packages\torchrl\data\replay_buffers\__init__.py", line 6, in <module>
    from .replay_buffers import (
  File "D:\anaconda\envs\easyrl\lib\site-packages\torchrl\data\replay_buffers\replay_buffers.py", line 20, in <module>
    from torchrl._torchrl import (
ImportError: DLL load failed: 找不到指定的程序。
```

> 找不到指定的程序: The specified module could not be found

## System info

Describe the characteristic of your environment:
 * Describe how the library was installed (pip, source, ...)
`pip install torchrl`

 * Python version
`3.7` 

 * Versions of any other relevant libraries

torchrl version: current newest: `0.1.0`

```python
import torchrl, numpy, sys
print(torchrl.__version__, numpy.__version__, sys.version, sys.platform)
```
output
`[error] 1.21.5 3.7.15`

## Additional context

`torch.cuda.is_available()` returns TRUE

## Checklist

- [x] I have checked that there is no similar issue in the repo (**required**)
- [x] I have read the [documentation](https://github.com/pytorch/rl/tree/main/docs/) (**required**)
- [x] I have provided a minimal working example to reproduce the bug (**required**)

**Comment by anonymouscnuser** [comment]
Solved in https://github.com/pytorch/rl/issues/975

The error message is different with `undefined symbol...` in Linux, so I opened this issue.
